###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    memcached:
        container_name: sf5-p3-memcached
        image: 'memcached:alpine'

    mailhog:
        container_name: sf5-p3-mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - '2011:8025'

    redis:
        container_name: sf5-p3-redis
        image: 'redis:alpine'

    database:
        container_name: sf5-p3-db
        image : donbrico/mysql-80-debian:v1.0.0
        working_dir: /application
        volumes:
            - ./.docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db-sf5-p3
            MYSQL_PASSWORD: root
        ports:
            - "2012:3306"
        tty: true

    webserver:
        container_name: sf5-p3-web
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2010:80'

    php-fpm:
        container_name: sf5-p3-php
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    node:
        build: phpdocker/node
        container_name: sf5-p3-node
        volumes:
            - .:/home/wwwroot/sf5-p3
        command: bash -c "yarn && yarn dev --watch"
        depends_on:
            - php-fpm

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf5-p3-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        ports:
            - "2013:80"
        links:
            - database
