<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240723130924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Data migration';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (1, 'Quaerat ad necessitatibus optio necessitatibus officia necessitatibus enim. Nostrum sunt officiis rem dolorem consequatur atque laborum. Eum placeat expedita consequuntur.', 'Quos nobis aspernatur molestias fugit. Ut dolorem ea eos et est. Dolores omnis nihil fugit esse et. Et laborum quam iure. Iure molestiae omnis molestiae asperiores ut minima. Odit odio occaecati rem quo omnis facilis.', 7236087, '2021-05-24 10:19:52', '1993-07-19 07:06:18', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (2, 'Quis quia quia modi eos. Ea recusandae accusantium est ullam provident cumque reiciendis quia. Labore quasi rerum architecto assumenda neque ea iusto.', 'Esse autem culpa adipisci illum. Consequatur amet doloribus totam velit qui voluptatem tempora. Voluptatibus dolores qui eligendi et illo. Laborum sed possimus in dolores ipsum. Quia iusto fugiat vero omnis rerum pariatur non.', 2218833, '1977-05-24 07:14:08', '1998-04-24 10:17:27', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (3, 'Quam saepe voluptas qui sequi. Dicta ut deleniti sunt laborum repudiandae fugiat in. Molestiae voluptatem ut autem enim voluptatem fugit.', 'Totam maxime quod dolorum reiciendis adipisci maiores. Cum qui inventore quis amet similique voluptatem. Quia dolores debitis repellat doloremque odio.', 2708, '2008-07-27 06:22:23', '1993-06-29 13:45:53', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (4, 'Rerum sint officiis perferendis consequatur suscipit accusantium explicabo. Dolor sit qui quis fugiat et sit. Quasi labore qui dolores omnis.', 'Est saepe est blanditiis recusandae et placeat. Aut unde sit incidunt sed velit. Ex fugiat sit ducimus est et quae.', 97078632, '1972-12-21 13:26:52', '1987-05-25 07:47:55', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (5, 'Rerum aut nam neque non eum ut quos. Dolor ut repudiandae eos fugiat nobis magni autem qui. Alias architecto dolores eius sit. Sunt harum quia temporibus deleniti explicabo amet itaque quas.', 'Dolore necessitatibus veniam vel sit. Praesentium distinctio quis laudantium eum maxime tempora commodi. Explicabo et quo eum tenetur. Aut repellat est dolorem magnam omnis fugiat temporibus.', 2006257, '1989-10-06 04:01:25', '1983-08-30 03:47:08', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (6, 'Consequatur quibusdam delectus eos dolores occaecati minima. Nostrum enim odit accusantium totam eius accusantium et. Atque earum aut temporibus blanditiis alias nemo.', 'Molestias veritatis totam recusandae laboriosam culpa quidem. Et veritatis velit quia tempora accusantium ut. Amet voluptatum et nisi molestiae dolor voluptatum. Sit quod sed in praesentium.', 6, '2003-04-26 12:48:33', '2016-08-02 05:38:36', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (7, 'Qui quod quibusdam atque sed eligendi excepturi error est. Beatae veniam corrupti optio quis aut est impedit. Sequi facere id alias deleniti.', 'Deleniti aliquid itaque ratione ut. Sunt voluptatibus dolorem nisi quia quod a. Voluptas rem illum veniam ut ea est sint.', 757067331, '1996-03-28 05:50:01', '1972-01-22 01:28:58', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (8, 'Quaerat doloribus sit doloremque consequuntur consequatur. Repellat adipisci corrupti quod odit. Aut aliquam officiis sit ducimus dolor et nostrum.', 'Officia sit enim qui ut voluptas. Cum eos blanditiis sunt aut maxime optio dolor. Dolorem cupiditate magni veniam est temporibus sit.', 28369, '1984-09-20 17:10:04', '2001-12-15 12:40:19', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (9, 'Enim qui beatae labore dolore omnis eaque. Culpa quibusdam occaecati expedita velit. Debitis et quo qui et non.', 'Impedit a voluptatibus nam ut ex. Facilis dolor repudiandae maiores sit. Reprehenderit excepturi et ratione quia.', 668795338, '1994-04-05 18:17:59', '1995-11-30 04:59:18', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (10, 'Quo et suscipit voluptates ut ab vel at. Sequi quo sit fugit quia et aut sed quo.', 'Nulla non necessitatibus amet non. A in aspernatur totam quis aut dolores possimus. In consectetur ut voluptas optio.', 6368, '2003-03-08 21:26:32', '1988-02-18 16:09:27', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (11, 'Quod sint id nostrum adipisci qui voluptatibus et. Enim animi facilis voluptatem et. Eum excepturi ab fugit ut amet delectus. Voluptatem distinctio et neque voluptates quis dolorem cupiditate.', 'Dolorem repellat sunt ut eos aut nesciunt. Quas maxime et non exercitationem. Similique aperiam temporibus iusto expedita consequatur dolorem consectetur ea. Aliquid corporis quas animi corrupti assumenda. Provident maxime reiciendis odit.', 2972, '2007-07-09 01:51:06', '1985-11-25 01:55:51', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (12, 'Cumque et ut distinctio. Error et recusandae iusto iste. Velit est dolorem aspernatur temporibus sed. Et consequatur est veritatis iure eius. Alias consequuntur eum quaerat esse quis.', 'Minus et pariatur quos beatae id non sapiente qui. Quasi qui placeat nulla rerum et quidem et.', 57, '2018-05-05 18:42:36', '1978-05-29 02:46:53', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (13, 'Aut sed dicta voluptatem animi in. Molestiae ut non ipsam. Nulla neque unde debitis aut totam sit tempore.', 'Quia id omnis non officiis placeat quasi. Sapiente expedita nihil voluptas quo similique aut mollitia. Veritatis ex sit eum nostrum sint. Qui eum quia asperiores est et rerum praesentium.', 637385, '1996-04-30 18:16:14', '2003-05-15 02:48:21', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (14, 'Esse quas doloribus consequatur quia quis sapiente officia. Suscipit culpa sint est alias.', 'Sit dolores nihil ea. Sed nulla aut necessitatibus adipisci optio. Repellendus dolor aut nobis rerum ut. Neque rerum mollitia aut et.', 566117, '1984-03-30 08:16:40', '2015-03-29 19:54:45', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (15, 'Eius rerum quia vel nemo autem tempora. Vero ad sed vero unde nam quibusdam pariatur. Nobis officiis reiciendis repellendus labore numquam et. Et dolor qui ex unde minus.', 'Ullam fuga omnis saepe placeat. Commodi iusto hic et omnis esse. Aut excepturi aut omnis dolores itaque. Id aut quas aliquam debitis. Reiciendis in est at facilis soluta repudiandae totam commodi. Dolores itaque rerum quasi quae deserunt totam.', 53, '2017-03-16 20:59:53', '2016-10-30 16:00:35', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (16, 'A praesentium dolorum et est optio quo nihil. Neque sit qui fugit eligendi est cumque veritatis. Temporibus quis voluptas ut.', 'Iusto corrupti sit hic inventore facere. Qui culpa architecto laudantium qui sint. Numquam minus vero perspiciatis. Aliquid iusto nihil ratione incidunt.', 4, '1993-08-04 15:55:19', '2005-11-03 13:03:15', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (17, 'Vitae eaque eligendi tenetur hic. Porro ad ducimus minus velit sequi iure eos. Voluptatem neque et ullam accusamus non. A sed numquam sit hic nihil ipsam.', 'Ut quia vero et. Sed ex in vel consequatur ipsum impedit. Maxime ipsam omnis accusantium impedit.', 5609919, '2009-03-21 06:05:30', '2022-02-06 09:44:16', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (18, 'Dolores aspernatur iste aspernatur officia animi possimus minus. Et corrupti quidem et alias. Molestias et id officiis odit hic assumenda illum.', 'Libero cum dolorem aut sed voluptatem ducimus. Voluptas cupiditate deleniti hic totam. Suscipit aut dolore non libero. Ea excepturi est quia ea ullam. Dolorum qui rerum corrupti ipsum odio omnis non eligendi. Quo dolorem reiciendis quae qui iure non.', 627, '1972-01-23 19:39:56', '2013-01-27 06:44:29', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (19, 'Voluptatum voluptatem facere dolor. Earum aperiam eveniet id. Impedit quaerat labore aliquid nisi eum aut tempora quas.', 'Natus incidunt consequatur tenetur sapiente saepe nulla ullam. Blanditiis id sunt suscipit odio. Inventore dolore quod ullam sunt recusandae. Doloribus fugiat commodi officia beatae animi voluptas quia. Hic totam dolor nemo unde neque.', 56459762, '2001-01-25 05:15:07', '2013-01-24 15:38:04', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (20, 'Et nesciunt nihil velit voluptatem quasi sit iure. Rem molestias omnis temporibus repellat aut reprehenderit non. Libero ducimus occaecati dolor optio. Eum vitae aliquid autem sunt aut.', 'Eum et quia ipsum. Cumque explicabo placeat eaque deleniti dolor qui et placeat. Quis dolor porro aut autem sequi nemo eveniet. Explicabo aut asperiores quia qui quam sunt. Enim qui sint eaque.', 12074, '2000-02-23 10:39:44', '2015-04-21 20:33:16', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (21, 'Quis quos minima nihil quia ad. Libero laboriosam repellendus libero illo. Dolore dolore veritatis voluptatem delectus ipsa et assumenda. In laboriosam mollitia corporis excepturi modi.', 'Quam rerum aut iste explicabo maiores dolor molestiae. Sed aut eum delectus fuga dolore. Est molestiae beatae eum veniam autem. Voluptatem saepe quia at sed optio consequatur repellendus.', 61822680, '1973-01-21 00:47:14', '1995-09-01 01:30:48', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (22, 'Dolore reiciendis sit error voluptas dolores fugiat a. Autem excepturi quia veritatis ut. Commodi ab veritatis provident dolorum et. Consectetur dicta qui fugiat totam iure.', 'Tempora officia adipisci rerum distinctio quas consequatur nesciunt autem. Doloremque sit in harum voluptatem sint veniam est. Ratione tenetur harum nihil quia vel.', 47586, '2009-06-06 01:42:15', '1988-09-26 22:02:21', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (23, 'Molestiae cumque dolorum repudiandae id. Quia dolores eum placeat velit repellat est.', 'Expedita ut voluptatibus suscipit ipsam. Molestias cumque numquam dolore velit quo occaecati occaecati id. Fuga maxime et sint nulla.', 168374, '2020-01-18 14:27:26', '2005-06-03 17:13:44', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (24, 'Quas fuga et deserunt est natus error dolorem. Sapiente qui vel vel labore quo sequi. Alias fugit sapiente odit modi. Ipsam corporis qui voluptas quam labore aliquam.', 'Soluta omnis illum eius eaque eum ea minus. Placeat dolorem vitae sint culpa ea mollitia et. Incidunt voluptatem totam quia reiciendis voluptatem. Dolorum nisi cum ipsam dolor. Modi et vel aperiam dolorem.', 122535, '1987-11-21 05:56:23', '2019-03-10 06:11:55', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (25, 'Laboriosam sint officiis ducimus voluptatem. Aut sed distinctio quis corporis autem nam. Voluptatibus eligendi doloribus consequuntur enim eius fuga porro. Ea similique laborum qui ratione.', 'Adipisci error pariatur quam veritatis ut ipsam voluptatibus. Tenetur neque fugiat et. Et voluptatem dolorem deserunt non vel debitis. Cumque aut ut quia expedita id. Velit sapiente aliquam neque.', 664296271, '1981-06-14 07:24:52', '1989-12-31 04:35:17', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (26, 'Doloribus eligendi dolor deserunt et animi laboriosam quo est. Nemo et rerum id. Doloremque pariatur repellat harum et.', 'Tempore eveniet eaque sunt vero debitis et. Facere itaque ad et non illum dicta vitae omnis. Quo et quis necessitatibus maiores deserunt voluptas nihil sint. Officia dicta ex maiores dolores vel.', 493, '1970-06-12 14:30:14', '1970-03-30 17:39:32', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (27, 'Sit temporibus sit laborum expedita quis. Sed temporibus incidunt et velit magnam aut. Ut ut vel qui aut placeat perferendis quia.', 'Laborum unde iusto illum labore eaque non quo aut. Sit magni autem vel quis exercitationem et omnis. Qui et maxime distinctio non tenetur quasi. Repudiandae eos optio vel dolorem quo.', 20, '1982-12-12 07:59:55', '1984-08-26 23:17:50', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (28, 'Necessitatibus id sit sed aut. Commodi et alias labore necessitatibus ut et quam. Soluta voluptate minima est praesentium quisquam. Tempora et nisi aut omnis minus qui.', 'Mollitia doloribus qui assumenda voluptatum sed veritatis quia. Et consectetur eius totam nesciunt. Et voluptatem labore totam deleniti minus et. Sed quisquam voluptatem in reiciendis natus rem.', 49350343, '2023-01-02 23:55:16', '1993-10-04 19:18:23', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (29, 'Magni facilis eos voluptas nihil rerum. Saepe corrupti fugiat distinctio dignissimos et.', 'Dolorem sapiente nihil non itaque voluptas hic nemo quibusdam. Omnis aspernatur numquam sunt exercitationem qui. Eligendi minima ipsum enim quo nulla est. Expedita reiciendis voluptatem aspernatur sequi quia vel dolorum. Nulla distinctio vel ut tempore.', 7352, '2004-08-27 18:23:42', '2017-06-07 07:27:52', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (30, 'Qui officia et possimus necessitatibus similique nesciunt ut. Saepe quaerat ea non velit. Eligendi aspernatur dolores placeat necessitatibus accusantium provident.', 'Iste dicta accusamus non. Natus praesentium animi dolores ipsum corporis. Et amet quidem voluptate totam consequatur veritatis.', 450, '2012-11-28 05:16:44', '1998-08-20 09:11:20', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (31, 'Eum et sit delectus quibusdam veritatis. Delectus dolores in laudantium aperiam odio. Sed beatae autem libero ratione assumenda minus et.', 'A placeat placeat quis minus perferendis autem laudantium inventore. Non possimus aut ex. Sit enim corporis omnis asperiores facere debitis ea. Quasi blanditiis tempore error aut itaque officiis ipsum.', 8494770, '2007-07-14 20:30:31', '1973-10-13 17:27:09', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (32, 'Ducimus inventore ea id doloremque dicta officiis. Labore ut id aliquam ut fugiat consequatur ut. Pariatur beatae magnam odio dolorem.', 'Ipsum suscipit voluptatibus voluptatum consequatur alias. Maiores tempora qui molestiae eos laudantium quaerat. Ut autem exercitationem mollitia est.', 2491061, '1970-11-29 04:30:55', '2023-11-28 07:54:53', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (33, 'Sit ad recusandae et est. Facilis quisquam quae natus est eaque. Asperiores alias tenetur deserunt beatae. Adipisci possimus ut quam magni.', 'Doloremque blanditiis et rerum velit. Et qui soluta vel ut molestiae. Deleniti eius excepturi ut deserunt fugit voluptate est.', 17433, '1990-01-15 01:45:55', '2007-09-12 01:27:14', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (34, 'Voluptate explicabo perferendis molestiae voluptatem. Laudantium velit veritatis aut quae quia consectetur. Unde sapiente ea sit suscipit odio sunt non.', 'Suscipit quam est id voluptatem in non aut. Culpa in doloribus labore. Voluptas aliquam sed expedita.', 63641, '2006-11-22 11:14:13', '1992-03-23 12:31:48', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (35, 'Aut sunt necessitatibus explicabo perferendis qui. Sed et corrupti iusto magni rem et fuga voluptatibus. Neque voluptatem qui repellendus. Ex id inventore quos omnis.', 'Eos est ullam praesentium dolores vel velit distinctio. Excepturi expedita est ratione nulla deserunt praesentium quos.', 934746, '1997-12-11 15:55:41', '1977-12-05 04:54:32', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (36, 'Accusamus tenetur repudiandae harum amet non ut suscipit. Nisi porro dolores animi culpa. Aperiam modi incidunt eius natus est reiciendis soluta.', 'Explicabo officiis deserunt quis sit aut. Ut dignissimos voluptatem et tempore qui iure et. Est ducimus ab ut iusto. Temporibus voluptates perferendis debitis autem ex possimus rerum.', 5292, '1970-04-16 10:20:12', '2009-12-06 15:19:24', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (37, 'Nulla ratione eligendi id ratione fuga. Et veritatis consequatur dignissimos expedita sint est. Deleniti ducimus natus quae laborum. Veritatis nisi possimus qui eum magni veniam alias.', 'Tenetur consequatur quaerat sunt consequatur natus repudiandae voluptas. Molestiae ex consequatur voluptatibus debitis commodi fugiat. Est perferendis vitae quidem quam omnis.', 17415, '1972-08-06 09:15:12', '2015-01-11 01:09:46', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (38, 'Quidem debitis ad enim minus error. Sint ut expedita rem et. Maiores iste dolorem ipsum fugit eius. Aut fugiat repellat adipisci. Eos quos earum qui porro. Sit et aspernatur porro.', 'Voluptatem praesentium et quia earum molestiae beatae recusandae officia. Tempora asperiores voluptates nemo qui saepe mollitia. Tempore voluptatem asperiores et ut.', 5817, '1984-04-10 20:51:50', '2012-01-10 19:49:59', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (39, 'Ut praesentium asperiores dolores minima voluptas dicta adipisci. Occaecati sint quod voluptatem non ipsa earum sed qui. Mollitia quibusdam in eveniet repudiandae dolor.', 'Atque impedit nemo quis maiores et modi. Eveniet dolores enim eius harum officia doloremque. Et in eum aut nobis dolorem. Autem ipsum distinctio corrupti quia esse. Voluptatem dicta sequi quo fuga. Laborum praesentium consequatur eum quidem qui.', 87685955, '2010-02-04 09:33:06', '1989-01-08 16:16:52', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (40, 'Voluptatem quos accusamus non aut. Culpa ea aut odit enim. Eos voluptatem molestiae magni vero quod.', 'Hic sunt et eligendi perferendis id quia. Exercitationem vel voluptas ut molestias. Quidem rerum iste sunt accusantium perferendis non voluptas. Quod aut error molestias tempora recusandae eos ipsam.', 3312326, '1999-03-29 22:20:35', '2000-04-30 02:08:25', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (41, 'Ut doloribus tempore hic illum repellendus deleniti necessitatibus. Delectus aut modi dolor aspernatur voluptates voluptatem est sunt. Ratione beatae qui voluptas autem molestiae et.', 'Ratione qui non magnam natus aut et. Odit molestiae sit modi quidem doloremque. Est et consequatur debitis suscipit aperiam. Omnis veniam et dolores et.', 295, '2003-06-24 04:58:20', '2017-11-26 04:15:18', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (42, 'Et vitae error consequatur debitis qui deserunt. Eligendi quis officiis et adipisci sit amet sunt.', 'Sint reiciendis eligendi hic error est. Impedit velit exercitationem sit molestiae non. Porro ipsam esse dicta repudiandae consequatur tempora. Voluptas omnis sint ut ut numquam rerum itaque. Rem repellendus id ut fuga occaecati nihil et.', 4562, '2004-06-23 00:45:07', '1971-09-11 15:12:24', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (43, 'At quo qui dolores eum ut dolorem et. Tempore voluptas perferendis quam. Quod illo officia similique dolor. Dolorum explicabo est ratione architecto ipsum tempora ut id.', 'Ipsa occaecati dolorum numquam dolorem. Voluptas fugit sit molestias ea dicta et quis nesciunt. Enim voluptatem sit et. Iure et nemo explicabo eveniet.', 803962, '2024-04-02 13:53:32', '1972-07-22 15:58:55', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (44, 'Molestias repudiandae necessitatibus expedita consequuntur. Nesciunt et sit mollitia vero. Qui sunt officiis quod et magni dolorum.', 'Tempore vel iste dignissimos. Voluptas natus est sit qui ut. Aut temporibus nulla veniam accusamus nemo est. Ab nostrum laborum modi porro facilis et dicta.', 193158, '1973-10-21 04:35:03', '1999-09-03 17:07:50', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (45, 'Dolorum aspernatur rem quia dolorum officia. Quasi nobis suscipit qui iure error quidem dolores. Exercitationem nesciunt enim qui voluptatem eum optio ratione porro. Quos et eveniet veniam.', 'Reprehenderit asperiores neque aut quasi doloremque doloremque. Veritatis quo velit voluptas. Consectetur sint inventore inventore aut architecto quia. Rerum placeat ea sit magni ea ipsa modi. Sed animi quos culpa illum odit.', 71128, '2005-07-29 19:47:10', '2009-01-13 21:28:34', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (46, 'Minus veniam voluptatum ipsam earum recusandae. Dolores repellendus consequatur laudantium eius suscipit. Placeat ipsum eligendi aut aut id quam.', 'Dolor commodi dolorum velit similique. Sed modi recusandae dolorem sit quas. Omnis optio exercitationem non unde. Est minus corporis quia quos eaque sunt repellendus qui.', 75, '1978-11-03 18:58:58', '2009-12-10 11:16:00', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (47, 'Magni explicabo eum culpa et dolor error. Et nisi laudantium consequatur et voluptate quia. Est repellat voluptas sed a neque. Quis iste necessitatibus qui et nostrum quisquam.', 'Quod sunt facilis similique qui rem inventore neque itaque. Molestias provident enim a sit harum et. Sunt impedit officia iusto molestiae. Maxime id qui tempora fugiat. Expedita et eos consequatur qui quis. Dolores a qui quam quia ut.', 299175596, '1986-07-02 08:51:15', '2003-04-11 10:46:25', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (48, 'Quam itaque ullam non ut sequi. Explicabo et ipsum sit quis corporis. Et sequi reiciendis id porro. Ullam molestias est at ducimus facilis eaque et quibusdam.', 'Labore blanditiis aut et. Expedita sed sed non natus. Beatae omnis quam et asperiores sunt soluta. Excepturi in omnis perspiciatis quos. Explicabo nihil sunt explicabo accusamus blanditiis autem.', 3762, '2012-02-05 00:24:50', '1981-06-14 22:18:30', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (49, 'Exercitationem aut adipisci voluptas qui voluptatibus. Voluptatem molestiae distinctio at nisi qui beatae. Nisi ex quia molestiae est odio reiciendis deserunt.', 'Est sit at error occaecati omnis aperiam tempore. Eum similique molestiae non dignissimos. Odio dolorem magni nihil inventore quis sint.', 99940854, '2018-07-12 23:31:26', '1981-07-07 01:33:59', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (50, 'Vel est et facilis sed ipsa provident rerum dolores. Cupiditate consequatur et et praesentium doloribus et et enim. Molestias fuga sit ut et voluptatum non. Laboriosam asperiores et quasi.', 'Delectus et rem amet animi quia tenetur. Ad laboriosam pariatur aut ducimus velit atque officiis. Quaerat incidunt voluptatem nostrum maiores quod.', 0, '2022-04-26 15:13:38', '2008-03-23 16:24:09', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (51, 'Exercitationem ex praesentium voluptatem atque ex. Pariatur facere est et ex quia. Vitae magnam quia fuga magni totam.', 'Asperiores sint nulla a aliquam explicabo omnis. Et non quia harum dolor. Ut repellat facere autem omnis aliquam necessitatibus. Corporis cupiditate aperiam a voluptatem quo qui quis.', 8, '1983-08-19 19:58:02', '1998-10-05 18:42:59', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (52, 'Cumque deleniti excepturi cupiditate sit sunt natus. Magnam consequuntur at aut nemo rem. Maxime qui autem officiis optio atque. Eum sapiente corporis placeat ea eius et.', 'Ut ratione et consectetur dolor cum nisi tempore. Placeat hic fuga non et nulla impedit. Excepturi inventore facilis minima adipisci nulla.', 392348, '2003-06-27 14:09:42', '1974-04-25 15:08:17', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (53, 'Velit voluptates nemo pariatur facere sed id. Quo enim a odio. Cupiditate esse ipsa accusantium ipsum modi eos. Enim qui temporibus est et odit. Dolores vel est mollitia sit.', 'Qui consectetur ipsum autem et provident incidunt odit. Aliquam laudantium eos dolore sed rem autem suscipit. Illum vero voluptatem qui est nisi.', 49, '1997-05-03 00:53:27', '2006-02-18 11:08:30', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (54, 'Error qui vero et sit dolorum enim voluptatem facere. Sapiente qui ut placeat voluptatum velit. Est aperiam odit quia pariatur esse tempora reiciendis. Expedita recusandae quia ut at alias.', 'Ut voluptas error voluptatem quasi quidem est ut. Maxime molestias adipisci eum magnam veniam. Voluptatum eos consequatur nihil autem voluptatem debitis. Enim porro ipsa dolore corporis.', 4365671, '1995-07-16 21:14:08', '1978-01-30 08:01:32', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (55, 'Nulla non ab at iusto vero. Architecto dolorem quae nisi laboriosam accusamus. Doloremque labore omnis omnis molestiae amet possimus omnis voluptates. Distinctio dolorum similique impedit.', 'Et vel quam quo quidem quaerat culpa fugiat. Expedita assumenda quae corporis dicta et. Laborum et esse et. Non dolor perspiciatis ipsum a nisi sint dolorem. Perspiciatis nulla non labore sed illo eius.', 588283660, '1976-06-06 09:41:52', '1995-05-21 13:26:20', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (56, 'Quis blanditiis quis qui alias. Et ad ipsum omnis sint dolores ut quo. Blanditiis velit deserunt nulla omnis iusto aut tenetur velit. Aspernatur quo nam tempora autem praesentium sint ipsum.', 'Consequatur et qui tempore corporis ducimus. Deserunt cupiditate placeat rerum. Non est soluta numquam nesciunt reiciendis.', 979966543, '2004-03-12 18:41:39', '2017-11-11 07:52:55', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (57, 'Perferendis occaecati iste tenetur. Ut fugit exercitationem minima voluptates velit. Et aut sit eum id asperiores et sunt omnis. Officiis ea aliquam qui voluptatum minus.', 'Sit veritatis corporis non iusto fugit. Placeat delectus expedita ex et eos et optio. Est ut et est est nihil.', 387755519, '2001-04-07 03:55:08', '2008-02-05 11:19:23', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (58, 'Voluptatem et non nulla at facere neque in qui. Asperiores aut quas sapiente sit possimus in iusto illo. Quis consequatur in maxime et.', 'Laborum quis et officia. Culpa autem id rerum quas.', 86941366, '1986-12-14 11:09:35', '1971-10-09 10:18:25', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (59, 'Occaecati magni voluptas dolorem. Ratione consequatur dolores est. Nam autem repudiandae quibusdam sunt dolor quis odit. Tempora libero voluptate aliquid sit accusamus.', 'Repellat qui repudiandae rerum dolores dolore consectetur. Qui iure veritatis voluptate nulla est. Iusto perferendis molestias in molestias et aliquid.', 264729281, '2015-09-18 18:52:00', '1970-03-02 14:13:10', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (60, 'Et vel id consequatur rerum. Rerum placeat minus quidem reprehenderit molestias similique. Accusamus harum atque minima.', 'Delectus magni repellendus consequuntur sit. Dicta ducimus ut reiciendis nam quaerat expedita aliquam et. Est voluptatibus aperiam impedit. Quo aperiam eius molestias nulla impedit aut ut voluptatem.', 35, '2016-09-27 06:44:01', '1991-11-16 04:04:39', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (61, 'Ducimus aut voluptas aliquid quo. Molestiae ex ut fugit ipsum. Saepe fugit voluptates culpa saepe porro praesentium.', 'Porro itaque qui occaecati earum. In et eveniet cumque temporibus. Voluptatem fugiat a sapiente. Reprehenderit sit omnis eos fugit quod sunt. Eos quia dolor placeat quae voluptate. Rem adipisci dolor quis esse laboriosam sequi est est.', 392, '1986-05-03 21:32:05', '2007-04-07 11:46:46', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (62, 'Vel sunt laudantium praesentium in eaque sed possimus. Ab minus autem aspernatur fugiat omnis expedita.', 'Odio laudantium est earum. Eos non ipsum in temporibus ea quibusdam et. Dolorem quas voluptatem asperiores et debitis et ducimus. Ex voluptas iste nostrum ea.', 806, '2005-04-27 10:36:06', '1978-10-04 07:29:38', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (63, 'Rerum facilis provident dolor libero aut assumenda rerum. Ullam aut nesciunt perspiciatis odio et et id.', 'Deserunt est explicabo aut occaecati. Consequatur consectetur voluptatem quae. Ut dicta officiis quidem magni rerum quo.', 5807336, '1988-08-08 20:28:50', '2019-01-04 21:55:14', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (64, 'Est saepe rem voluptatem ullam. Vel nostrum porro ut dolore. Explicabo qui aspernatur excepturi rerum animi necessitatibus optio.', 'Est possimus aspernatur tenetur esse consequatur beatae aut. Sed temporibus ipsam ut quam numquam veritatis. Placeat eaque vitae aut dicta et. In qui voluptatum tempora aperiam.', 11, '1974-08-04 22:05:10', '1974-05-31 19:02:52', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (65, 'Enim non in inventore earum et. Quia maxime iusto amet dolores veritatis. Aut praesentium qui necessitatibus dolores tenetur vero.', 'Nobis in totam dignissimos eligendi sit. Commodi quia nulla magni molestiae blanditiis quod qui amet. Sequi possimus qui saepe autem voluptatibus libero est.', 730, '1984-09-13 13:22:00', '1975-08-31 15:02:18', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (66, 'Voluptatem quia voluptas ex aut. Necessitatibus atque reiciendis voluptatem dolorem. Quidem iste odio est. Ex vel ut nihil commodi hic. Odit expedita delectus aut quaerat quis.', 'Repellat officia explicabo aut. Aliquid aspernatur veritatis adipisci porro ducimus explicabo. Quibusdam natus quos aut dolores eos asperiores animi a.', 81186, '2018-08-14 15:15:13', '2009-01-09 10:58:39', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (67, 'Ut iusto repudiandae quis quo. Aliquam qui vero quia facere. Sed id ipsa qui repellat vel quaerat.', 'Consequatur labore vero mollitia exercitationem quia qui. Dolorem quibusdam assumenda officiis nihil. Sint non ullam expedita quod harum voluptatum occaecati.', 256, '1979-02-07 22:36:42', '1972-10-22 23:12:15', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (68, 'Quia dolore totam sunt quae occaecati est dolores. Et magni quaerat officia qui perspiciatis. Delectus facilis dolorem earum consequuntur soluta. Facere aut error est unde voluptatibus est eius est.', 'Nemo architecto molestias sed voluptas laboriosam. Velit et nemo et doloremque deserunt. Aut aliquid sunt expedita blanditiis qui.', 208980, '1974-01-26 01:55:17', '1998-06-04 05:12:21', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (69, 'Necessitatibus quo odit eligendi voluptatem repellendus. Eius corporis velit recusandae error.', 'Voluptates animi debitis et facere iusto et repellat. Quis et similique enim architecto. Sapiente et tempore quidem possimus. Et consequatur praesentium et. Similique est nobis id aut alias maxime vero.', 7188848, '2013-08-21 21:58:58', '2006-05-26 21:29:18', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (70, 'Rem sunt aut ex illo aut voluptatum. Aut nihil nisi magni placeat voluptas quas. Explicabo ipsam necessitatibus et ut culpa reprehenderit.', 'Voluptatum maxime asperiores facilis dolorum et. Est sequi consequatur id repellendus. Accusantium quis velit et non voluptatibus animi. Expedita tempore ipsam aperiam quos.', 366073103, '1983-03-31 13:16:56', '2022-10-18 01:08:48', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (71, 'Doloremque sint possimus ex dolor officia. Aut occaecati et earum quam. Porro qui placeat et quasi.', 'Dicta cumque ex ipsum quis rerum voluptatem a. Numquam accusamus numquam sit aliquid ea qui. Odit quaerat sequi quia nihil veniam perspiciatis. Labore est molestiae vel voluptatem suscipit quo.', 36, '1986-07-21 13:41:24', '1975-06-15 13:53:20', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (72, 'Illo ipsum quo dolor soluta. Voluptas dolor ut fuga qui laboriosam repudiandae sit. Veritatis a at in expedita laudantium libero.', 'Et ut doloribus omnis et eaque ullam aliquam. Distinctio nostrum qui consectetur voluptas. Nihil accusamus qui ab nesciunt veritatis modi. Repellat soluta minus aut dolor et. Velit est harum ducimus eum possimus id.', 37, '1992-06-10 08:00:12', '1997-05-06 07:38:57', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (73, 'Maxime enim natus a molestiae fugiat. Consequatur possimus beatae tempore. Repudiandae sit pariatur sed nemo.', 'Laboriosam minima et quas rerum aut modi. Ab ut nostrum ipsum error illum et. Perspiciatis libero officiis architecto eaque. Error ducimus autem eligendi est. Et consequuntur similique rerum eos at sunt.', 7, '1982-06-05 02:48:10', '2014-03-20 08:40:56', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (74, 'Unde quaerat omnis rerum optio. Ducimus dicta omnis velit nostrum odio qui voluptate laborum. Dolores reiciendis dolores dolor quam beatae reprehenderit qui quia. Odio nemo distinctio similique.', 'Tempore dolores non ad recusandae ex vel. Officia voluptates nostrum perspiciatis occaecati odio tenetur dolores. Placeat voluptas fugit quibusdam nulla qui perferendis. Iste ad exercitationem dolore autem eius iusto natus.', 3894, '1999-10-19 02:08:37', '1997-01-13 16:34:32', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (75, 'Eum quia dolorem omnis ut perspiciatis repellat. Eum ut perferendis cupiditate rerum et id nostrum.', 'Dolorum magnam illo ad illum dolorem. Et corporis ullam et maiores voluptatem. Ut deserunt facere sed modi aut quod praesentium.', 7372, '1993-09-29 03:16:03', '1987-04-12 14:16:36', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (76, 'Quaerat incidunt saepe ut quo voluptatem pariatur qui. Et voluptatibus delectus at ut possimus. Atque ipsam velit eum dolores. Saepe voluptas vitae autem aliquid labore nisi.', 'Impedit quod aut harum dolore. Quo voluptatem non consequatur perspiciatis voluptas. Exercitationem ut magnam velit veniam est. Quia corrupti qui ullam. Placeat qui cum natus sit sapiente odit.', 9, '1984-05-13 06:42:17', '1971-04-23 10:31:53', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (77, 'Omnis consequatur quibusdam dolorem quas odio architecto provident itaque. Dolore tempore rerum sed est aut tenetur qui. Quas quibusdam fugiat reiciendis temporibus accusantium cumque aut dolorem.', 'Aut iusto impedit eveniet voluptas. Itaque error qui numquam necessitatibus. Impedit totam laudantium modi cupiditate corrupti. Magni et aut excepturi ea. Impedit totam consequuntur et explicabo quo id rerum.', 56813297, '2003-05-07 04:36:34', '1976-08-27 20:28:30', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (78, 'Asperiores ut facilis omnis aut et. Itaque sed consequatur doloremque ex reiciendis. Quod recusandae ut dignissimos consectetur sed voluptatem laudantium. Inventore unde velit dolore.', 'Molestiae aut quo magnam corporis. Id accusamus voluptas qui occaecati. Nulla quia odio possimus et a necessitatibus. Odio et reprehenderit reprehenderit delectus aut voluptas necessitatibus. Iste expedita placeat ducimus quae aliquid at.', 5, '2020-05-19 22:46:33', '1983-09-29 19:30:02', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (79, 'Qui et mollitia ipsam omnis. Voluptates natus rem eos molestiae repellat deleniti. Doloribus maxime est nobis atque harum quibusdam. Qui id voluptatem velit aut.', 'Dicta alias pariatur eligendi soluta doloribus tempore minima. Nihil ipsa sed odio voluptatem. Delectus quidem quis hic.', 1, '1996-09-27 08:37:11', '1985-10-13 03:42:28', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (80, 'Autem consequatur iure a aut debitis qui. Nesciunt ipsum quo quas unde. Dolor a molestiae architecto dolor. Molestiae deserunt et debitis totam.', 'Eos voluptate totam animi ea omnis quis pariatur. Id eius vitae qui nostrum. Assumenda voluptatem aut natus voluptatem.', 97571198, '2020-09-05 08:32:30', '1984-07-29 21:00:13', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (81, 'Ipsam quasi nam enim reiciendis eaque veritatis ut. Sequi eos sed quam voluptatum. Velit harum beatae qui velit beatae sed assumenda. Autem vel voluptatem nihil dicta sint cumque.', 'Ad nihil ut inventore impedit sit qui neque. Labore vitae qui temporibus quam ut. Quis consequuntur aut sit quisquam. Fugit dolorum possimus rerum voluptatem repellat occaecati voluptate.', 312481, '2016-07-06 22:11:33', '1977-04-20 19:05:49', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (82, 'Consequuntur odio voluptates quaerat ut tenetur quis. Temporibus soluta nihil cumque aperiam deleniti fugit nulla. Quia deleniti sint qui magni. Omnis dolorum qui possimus temporibus nulla nam.', 'Delectus aut in iure quia recusandae. Expedita quaerat placeat sit omnis. Non a nobis et consequatur eos a iure.', 5968, '2011-10-16 14:53:59', '1975-04-25 23:27:38', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (83, 'Quia delectus enim impedit distinctio. Nam deserunt fuga qui nihil autem eveniet. Voluptate ipsum nobis hic voluptas.', 'Nisi dignissimos iste blanditiis adipisci perspiciatis. Quae blanditiis exercitationem voluptatem voluptates voluptas et. Nulla vero aut corporis rerum sunt libero. Occaecati et aut rerum officia distinctio.', 722588, '2004-09-05 12:05:54', '1993-05-25 04:10:25', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (84, 'Fugit inventore porro aut consectetur ipsum. Nesciunt qui expedita ab facere provident rem sequi. Quisquam facilis vel et.', 'Qui vitae voluptas omnis explicabo. Aut odit amet accusantium aut necessitatibus molestiae sit. Nihil rerum ex aliquam corporis veritatis. Id voluptatibus quidem corporis voluptate.', 1947802, '1972-05-07 16:53:55', '1970-06-29 04:09:58', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (85, 'Possimus vel sunt velit totam ad. Aut aut aperiam laudantium deserunt eaque. Non porro delectus maxime. Corrupti rerum voluptas magni fuga est. Nulla nihil blanditiis ad velit dolores quo aliquid.', 'Minima est est eligendi officiis quos sed praesentium saepe. Ratione aperiam quo temporibus dicta. Aut laboriosam dolorum excepturi cumque.', 9899, '1985-05-23 10:17:26', '2009-01-01 22:49:12', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (86, 'Placeat eum laborum cupiditate corrupti tenetur odit. Nam accusantium praesentium ex sit incidunt. Dolorem et iusto voluptatem beatae. Nobis occaecati corporis ea pariatur et aut molestiae.', 'Praesentium provident amet explicabo ab. Fugiat et autem tempore sint quia. Non dignissimos et explicabo eum voluptatum. Ea unde illum velit eaque sapiente.', 85, '2005-03-20 05:03:22', '1973-03-09 06:59:30', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (87, 'Magni molestiae et est laboriosam. Atque totam officia perspiciatis. Doloremque ex corrupti expedita recusandae.', 'Voluptatem itaque quaerat laborum culpa sint. Vel repudiandae ducimus molestias consequatur. Cum ut ullam fugiat a autem aperiam. Non nesciunt rerum nihil laboriosam nihil. Ut reprehenderit eveniet tempore hic iure. Beatae nostrum et nisi ut dolor autem.', 666779, '1980-02-01 06:36:41', '2001-01-11 17:10:30', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (88, 'Eum quo sed omnis iusto quidem sunt. Aut vel quia temporibus voluptas veniam. Quae maiores nemo debitis. Dolorem eos facilis qui et.', 'Eius dolorem aut minima porro quibusdam. Accusantium omnis tempora harum occaecati quis ea. Aut tempore dolorem quia odit. Quia quaerat omnis dicta veritatis iste odio. Sed maxime rerum facilis excepturi officia suscipit impedit.', 52597, '2011-09-14 01:13:45', '1988-08-02 04:26:23', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (89, 'Dolor debitis nostrum voluptatem debitis nemo odio modi. Reprehenderit nostrum consequatur incidunt ipsum ut quam. Enim nostrum eum amet quas.', 'Et aliquam et ex eum et quibusdam eligendi. In aut et veniam rerum qui eos amet. Quam omnis odio distinctio non voluptas. Facilis id expedita corporis officia et rerum ducimus. Sed quo voluptatem illo in.', 451, '2021-03-08 01:24:45', '1997-07-15 13:51:26', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (90, 'Id laborum et autem et. Provident similique ipsa at harum vitae quasi enim. Error aperiam ut saepe.', 'Ea quisquam fugit voluptates corporis voluptatum quos excepturi. Magnam iusto molestiae dicta. Omnis eos est rerum vero. Delectus quisquam adipisci praesentium nesciunt culpa omnis.', 171097604, '1985-04-13 10:32:18', '2007-04-30 21:44:08', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (91, 'Illo facilis voluptates odit qui qui dolore. Quo distinctio qui voluptatem provident iusto iusto enim. Ut est laborum aut aliquam eos impedit.', 'Ipsum iusto adipisci molestiae facere corporis. Dignissimos suscipit modi modi sit et. Voluptatibus doloribus eius ea autem et nam. Voluptatem animi reiciendis magni maiores ut animi beatae rerum. Eos velit eos hic temporibus dignissimos possimus et.', 95437873, '2004-11-08 22:49:31', '2016-03-17 18:56:08', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (92, 'Necessitatibus et sunt autem dolor laborum ut ut et. Esse voluptates minus rerum alias beatae omnis. Nemo maxime reiciendis dolores amet dolores vel.', 'Labore blanditiis vel qui at optio molestias voluptas. Expedita qui molestiae consectetur. Repellat dolorem dolorum deserunt nemo autem. Iusto id totam et. In molestiae rerum ea asperiores ducimus esse.', 423, '1973-07-06 17:23:57', '2010-10-13 11:20:44', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (93, 'Dolor ab accusamus voluptatum. Omnis cupiditate culpa adipisci nobis cum aut. Qui rerum beatae ut. Distinctio corrupti totam dolorem porro.', 'Quidem molestiae et saepe quibusdam blanditiis. Dolor debitis nesciunt sunt fugit ut eum aliquam ipsa. Rerum dignissimos esse qui. Non earum magni officia ea autem.', 71, '1987-10-22 03:56:34', '2021-10-30 02:20:44', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (94, 'Soluta alias ducimus qui et est reiciendis aut. Id voluptatem impedit architecto placeat. Omnis vitae rerum omnis dicta tempore quo aut eveniet.', 'Laborum aliquam molestiae molestiae est aliquid. Et porro voluptates et atque quia molestiae placeat. Sint iste beatae occaecati autem soluta quo commodi voluptatem.', 548439, '1999-02-08 16:10:07', '1996-10-06 16:54:26', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (95, 'Ducimus quibusdam velit sed quibusdam beatae odit eius. Voluptatum porro minus illum facilis praesentium rerum. Necessitatibus deleniti aliquid aspernatur sunt reiciendis repellendus.', 'Libero quaerat tempore voluptas qui consequatur reiciendis. Ea voluptatibus natus nihil et delectus.', 765020893, '2001-04-03 05:30:50', '1970-01-02 19:45:05', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (96, 'Voluptas dolorem suscipit eos ex. Similique quae esse ut voluptatum laboriosam quos perspiciatis. Facere est est delectus tenetur repellat et.', 'Qui sint eaque non. Ut quo quo molestiae sapiente. Rerum modi sequi vero soluta impedit dolore.', 374, '2000-07-31 00:29:03', '1993-07-25 20:48:06', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (97, 'Laboriosam hic qui voluptatem magni non occaecati. Vel et reiciendis sit est et. Perferendis voluptatibus quis perferendis maiores mollitia hic voluptatem.', 'Harum eaque recusandae est totam. Quasi tenetur voluptates quia labore nam voluptates. Perspiciatis omnis eos aliquid repudiandae ea occaecati.', 165, '2014-11-10 19:42:35', '1978-09-15 21:48:59', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (98, 'Labore incidunt id nam rerum deleniti architecto id. Et numquam modi sunt modi deserunt. Ut praesentium aut autem soluta eos ut enim.', 'Nesciunt non voluptatibus perferendis tempore qui necessitatibus iure. Mollitia odit quis similique repudiandae iste. Nesciunt ut ipsam eius voluptas sunt est cumque aut. Aspernatur nam voluptatem eligendi.', 2617, '2002-03-17 07:17:10', '1988-06-23 07:25:11', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (99, 'Suscipit ea voluptates omnis est. Vel harum exercitationem ratione voluptate dolorum voluptas odio. Repudiandae voluptate dignissimos sunt sit velit fugiat voluptates. Et ipsa eos et doloremque.', 'Aut architecto fugit expedita sit et iste et. Nobis aut sit aut minus nobis natus. Et sunt qui est atque. Qui saepe dolor quod explicabo at numquam alias asperiores. Amet autem fuga aut doloribus hic saepe.', 368, '1982-12-03 19:03:14', '2003-06-22 07:21:54', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (100, 'Illum voluptatem pariatur at earum est et ipsam saepe. Velit in facere quia maiores neque itaque quasi esse. Hic qui dolorem et sit et eius rerum qui.', 'Pariatur fugit ipsa porro labore maxime. Ut provident vel illum. Omnis id qui rem minima dolorem.', 33456155, '2019-05-08 16:58:53', '2005-08-15 06:00:27', 15)");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (1, 'Harum error corporis odit in ipsum quo unde maiores. Et quia iusto ex praesentium ducimus odio. Ut consectetur aut earum repellat vel.', 'Qui dolores qui sed sed est. Facilis iste rerum commodi est. Sint explicabo qui quaerat sed sunt quaerat. Tenetur blanditiis error sequi praesentium neque quos facilis.', 'At quidem sed est ut est ullam. Necessitatibus molestias atque aut quisquam voluptatem enim. Esse et sapiente ad.', NULL, 58897609, '1975-02-14 11:06:47', '1993-05-23 15:54:53')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (2, 'Aut voluptatibus iste ea laboriosam. Voluptatem dicta et exercitationem voluptas ullam. Minima provident cumque ipsum consequatur in quia. Ut nostrum sit doloribus porro et. Consequuntur aut nulla similique harum nisi ea. Inventore consequuntur est ab.', 'Nihil et eius et sequi quis et perspiciatis ut. Quisquam quo ea culpa non ut dolorem. Qui itaque dolor aut maxime ullam ipsam vel laborum.', 'Ut optio numquam est omnis qui. Sit qui quia est et placeat. Rerum asperiores in sed corrupti enim aut ut porro. Natus voluptate voluptate quae velit molestiae qui dolorem.', NULL, 11, '1982-03-17 00:41:34', '1985-11-30 04:05:30')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (3, 'Itaque qui quibusdam quam et vel quo nostrum. Fuga recusandae et et nisi exercitationem magnam. Voluptas illum at id nulla et minima ratione ab. Asperiores qui aut omnis vero cupiditate dolore in aut.', 'Unde molestiae quis accusamus. Sint laudantium placeat nemo possimus. Incidunt soluta eum incidunt ut nulla tempora est nihil. Distinctio asperiores eius rerum qui quia natus.', 'Nesciunt vel vel autem accusantium. Perferendis cupiditate mollitia consequatur in voluptatem consequatur. Sint est et vel reprehenderit ratione eos cumque aut.', NULL, 98023535, '2006-07-25 23:16:58', '1972-06-14 14:04:00')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (4, 'Expedita occaecati ut recusandae officiis aliquid repellat asperiores. Et corrupti illo dignissimos et id iure ut. Dolorum rerum libero culpa est dolorem est. Fugit provident rem consequuntur. Possimus itaque nulla error quis totam est dolorum.', 'Ad assumenda vitae a corporis. Maxime quis voluptas corporis reiciendis. Ipsa molestiae quia a soluta aspernatur maiores.', 'Quod cum consequatur laborum exercitationem eos nostrum. Voluptatum perferendis saepe voluptatem eos et culpa itaque ea.', NULL, 8454, '2017-06-25 14:27:25', '2007-06-20 03:19:30')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (5, 'Omnis dolor sed error fugit voluptatem atque. Reiciendis et illo commodi et nobis minima animi aut.', 'Earum temporibus est accusantium ducimus tempore. Hic ad delectus voluptatibus sit incidunt. Atque quas at ea laudantium dolores. Rem voluptatem voluptas quia dolores qui et odio.', 'Vel ut nisi maiores pariatur molestias. Aut tempore ipsam voluptatem dolorem et. Cum magnam in odio aliquam alias corporis enim. Aliquam eius qui et autem est est et.', NULL, 207, '2023-11-09 22:54:54', '1975-03-08 17:26:10')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (6, 'Praesentium placeat adipisci facilis et. Qui dolor explicabo nihil est totam eligendi ut et. Ut sed impedit ipsum sunt. Quis aut rerum et.', 'Enim non rerum repudiandae molestias dignissimos eveniet. Non natus vel sit quis. Numquam dolorum error ipsam. Itaque nam iure aut iusto quidem. Dolor nesciunt adipisci dolorem reprehenderit.', 'Sit soluta ut consequatur. Nihil nobis pariatur molestiae quia doloribus. Quisquam aliquid facilis corporis rerum assumenda ullam officia. Ullam qui qui officiis iusto ad. Modi corporis eos amet in.', NULL, 0, '1979-03-25 18:58:46', '1995-05-15 09:01:13')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (7, 'Nihil sit nobis cum explicabo illo aut distinctio. Doloribus exercitationem nulla expedita cupiditate perspiciatis. Officia nobis molestias eveniet laboriosam sapiente. Quia iusto porro quod optio.', 'Et magni perferendis possimus necessitatibus sed repellendus dignissimos placeat. Nisi enim cupiditate et qui neque. Dolores sint alias sequi et. Ut ut magni autem. Dolores voluptatem commodi ipsa blanditiis temporibus.', 'Dolorem et libero dolorem numquam dolores. Non molestiae excepturi debitis ea. Voluptates velit deserunt optio officia. Aspernatur et veniam adipisci ad veritatis eius.', NULL, 7380, '1998-11-08 02:09:12', '1972-02-04 17:12:36')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (8, 'Incidunt qui omnis qui reiciendis. Pariatur sunt dolorem eveniet deserunt fuga nostrum minima. Perspiciatis dicta sapiente perspiciatis. Eveniet sed et quia animi eaque.', 'Labore eius et voluptates eum. Voluptate dolorum ullam harum illum porro reprehenderit sapiente. Sint dicta temporibus rerum quasi dignissimos veritatis occaecati hic. Adipisci illo sequi quibusdam quia excepturi nam corrupti.', 'Minus omnis placeat dignissimos eaque quos. Distinctio quisquam dolorem aut. Animi in perferendis et facilis. Expedita in fugit ratione ut in ad est.', NULL, 483566534, '1973-12-23 12:41:11', '1982-02-19 17:26:51')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (9, 'Rem culpa ad aperiam est quo sapiente. Maxime cumque quia voluptates ea id. Repudiandae nam sunt accusantium ea dolorem vel non.', 'Itaque debitis error vitae et consequatur. Explicabo et dolore deserunt reprehenderit deserunt et. Atque fuga reprehenderit officia qui eos. Minima aut voluptas sint nam asperiores. Delectus qui sed laboriosam voluptas.', 'Ut labore accusamus labore voluptatem totam quia. Vel aut fuga dolorem sequi itaque eaque. Sed quasi fugiat incidunt praesentium sed nam molestiae est. Esse aperiam non dolorem et nobis eligendi.', NULL, 19, '1970-06-23 18:42:04', '2017-08-16 01:22:34')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (10, 'Magnam beatae non quibusdam qui. Dolorem molestiae velit sit quas laborum. Incidunt perspiciatis eius iusto aliquid omnis.', 'Est rerum saepe illum quia dicta. Quos veritatis ipsa in accusantium. Accusantium quis quia cupiditate nihil dolorem officia. Voluptas impedit culpa delectus praesentium. Quia et saepe est.', 'Dolore ullam inventore dolorem ducimus dolore. Pariatur sint sed aut aut ducimus illum repudiandae. Voluptatem et cum consequatur.', NULL, 804, '1985-01-06 04:32:28', '2008-05-12 09:45:34')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (11, 'Dolorum minus molestiae libero sint quam numquam. Quia dignissimos quo voluptate repudiandae. Neque porro ut nostrum fugiat et eos. Blanditiis laborum cum distinctio assumenda. Perferendis sapiente consequatur excepturi rem quod.', 'Pariatur in id commodi. Aliquam id minima aut perferendis minus aut. Dicta libero ut mollitia veritatis officia dolorem exercitationem. Blanditiis earum ut ut.', 'Nulla ut dolor deserunt ut. Quasi nemo autem repudiandae labore et expedita.', NULL, 41, '1978-04-09 03:05:30', '2004-02-04 00:59:14')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (12, 'Labore ut distinctio reiciendis est et quia architecto. Deserunt vero totam vel iste ipsum non. Ex unde consequatur recusandae quam ut id. Eum eos aliquam et rerum.', 'Magnam reprehenderit alias molestiae voluptatum quam deleniti dolor. Ut ut nemo quae reiciendis inventore consequuntur. Suscipit quae repellendus ut qui. Impedit ipsa quae culpa rerum placeat quia pariatur.', 'Neque excepturi natus consequatur quis placeat. Tempore reiciendis expedita sapiente mollitia. Vel nemo impedit et perferendis iusto. Qui dolorum dolorem recusandae autem nulla similique ipsam.', NULL, 367, '1990-04-17 10:54:24', '2004-01-20 21:42:47')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (13, 'Est ab sed tempora totam. Et ea excepturi dolorem. Ut quisquam quam aut. Quam eos libero rerum neque hic. Qui asperiores harum aut et officia et. Dolorum ut minus reiciendis cum.', 'Deserunt consequatur eos quo rerum. Eos commodi adipisci sed ut labore temporibus non. Consectetur qui voluptatem possimus tempora. Et ipsa quaerat debitis et repellendus. Eum voluptate facere aperiam rerum enim.', 'Enim vel dolores voluptatem officiis sed ea in mollitia. Neque sed fugiat et delectus. Quas ad et in ut animi rem. Nulla quasi et et ea optio ut.', NULL, 444709, '2004-04-23 23:03:43', '1987-01-12 02:15:29')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (14, 'Et ut sint et in occaecati. Debitis sit magni adipisci totam. Id pariatur nam hic aut facilis id aut. Doloremque amet consequatur iusto.', 'Culpa consequuntur autem officiis. Quasi aut dicta veniam libero laudantium temporibus facilis. Amet ab ratione ipsum veritatis. Dolor aliquid eaque unde magnam eius.', 'Sed et placeat quidem id est dignissimos impedit. Sint quia sint et veritatis et quis rerum. Ut illum numquam aut error iste. Modi temporibus qui inventore quidem dolorem aliquam ea esse.', NULL, 5221350, '1992-09-18 05:11:19', '1987-12-13 03:00:25')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (15, 'Distinctio qui facere maiores explicabo omnis temporibus. Distinctio ut earum porro aut cumque ipsam sint dolorum. Corporis maxime optio itaque enim beatae blanditiis aut.', 'Quae perspiciatis quisquam et. Nisi quam repudiandae similique explicabo. Eaque aut veritatis vel non voluptate iure consectetur.', 'Accusantium dolorum quidem possimus est iste fugiat. Molestias nulla possimus consectetur voluptatem qui voluptatibus. Consequatur alias est odio et corrupti aut.', NULL, 78, '1987-11-05 13:39:41', '2019-01-21 10:02:40')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (16, 'Quia eius consequatur impedit quibusdam. Cumque explicabo sed eius repudiandae voluptate cum dolor. Eaque sed sit et sunt.', 'Recusandae molestias velit laudantium magnam occaecati animi. Rerum a sint consequatur necessitatibus. Repellendus animi molestiae enim tempore suscipit. Nam voluptas iure tempora quasi consequatur iste aut qui.', 'In consequatur cumque voluptates deleniti consectetur. Corrupti aut laboriosam minus in. Veniam porro et vel nobis voluptas rerum dolore magni. Et cupiditate labore consequatur qui nihil.', NULL, 84, '2005-12-29 11:49:47', '1977-12-20 12:47:41')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (17, 'Accusantium illum odio dolorem nam nobis quibusdam. Ut non voluptatem unde aliquam possimus amet. Temporibus rem dolorum expedita. Adipisci quidem et quam aliquid iusto culpa. Sapiente nemo molestiae dicta suscipit debitis autem nostrum.', 'Quia est dolores eveniet enim quod qui occaecati. Numquam sunt sint voluptas qui repellat itaque ut id. Id vel necessitatibus voluptas officia qui voluptas ut.', 'Eligendi reiciendis nulla rerum id et. Consequatur qui deserunt quia non incidunt aperiam. Distinctio minus temporibus enim. Ea distinctio possimus aspernatur enim minima aut.', NULL, 77, '2000-11-19 09:18:00', '2022-10-17 09:45:25')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (18, 'Commodi dignissimos cupiditate architecto vel et modi. Temporibus magnam quia voluptatum amet tempora minus. At optio excepturi ullam.', 'Cum non quasi doloribus explicabo eligendi dolor. In aperiam et architecto. Totam aut corrupti consequatur error laudantium temporibus.', 'Eos sed soluta maxime et facilis. Quos repellat alias quaerat ipsum. Voluptatem laudantium est et sed natus.', NULL, 92870, '2023-12-27 07:32:53', '2005-09-14 22:18:55')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (19, 'Non ipsum quidem nihil asperiores nihil. Omnis et beatae ad et neque. Quo aut temporibus et sit voluptatem qui qui. Impedit et officiis sapiente dolorem soluta.', 'Quidem et sunt suscipit nihil cum ex qui. Omnis labore et commodi.', 'Ratione nihil non deleniti doloribus vel rerum. Quae voluptatem dolorem ut non consectetur nostrum dolor. Unde aliquid totam officia voluptatem. Nemo itaque molestias possimus delectus dolorum.', NULL, 248, '1980-11-27 08:16:57', '1988-03-09 01:42:35')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (20, 'Ratione sint laboriosam quasi provident repudiandae. Mollitia vero eos eligendi sit libero rerum nihil. Suscipit et magni perferendis in qui temporibus aliquid.', 'Tempora eaque pariatur sed iste. Sed accusamus facilis aut corporis sit saepe amet. Dolorem quae quaerat et distinctio nobis eum illo. Eos et rem harum dolorem eos sint aut.', 'Ut culpa culpa in cumque accusamus quo. Distinctio voluptatem dolorem ut voluptas temporibus. Optio pariatur nobis culpa saepe.', NULL, 641341461, '1977-06-16 13:24:39', '2021-03-23 03:29:02')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (21, 'Sunt necessitatibus ut praesentium qui possimus consectetur. Mollitia aperiam veniam nihil fugiat iusto dolorum repellendus. Impedit blanditiis qui qui et voluptatem voluptatem non est.', 'Voluptatibus velit sit laborum ut. Aut ullam impedit ipsum incidunt accusantium expedita aut. Quia voluptates doloremque sint rerum. Quae quo et saepe sit et dolor.', 'Odit tempore et eveniet ducimus. Numquam ut amet explicabo accusantium. Consequatur fugit voluptatem sit hic aliquid vel. Vel qui vero accusantium aperiam qui repudiandae quisquam occaecati.', NULL, 416974, '2004-08-31 20:15:02', '2021-10-06 02:43:10')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (22, 'Aspernatur sed dicta voluptatibus. Minima pariatur non natus velit quia praesentium. Sed quidem voluptatibus reiciendis distinctio. Ut vel alias veniam aliquid blanditiis ut. Dignissimos voluptatem facilis consequatur rerum autem possimus.', 'Sed itaque alias provident libero vel harum nihil odio. In sapiente dolore impedit dolores enim reprehenderit. Est qui molestias aliquam illo nihil. Quod nihil ut ut numquam sint dolor assumenda.', 'Eum quis et unde odio aut tenetur. Quas ullam aliquam minus ad quisquam nisi.', NULL, 83522521, '1992-10-06 16:28:54', '2002-02-07 22:40:47')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (23, 'Est suscipit id aut id ut minima fugit vero. Ad error rem a est ut esse non. Neque deleniti est sint quisquam voluptatum. Nemo id et sint dicta sequi et incidunt.', 'Modi molestias facilis ipsa est accusamus. Minus impedit officia dolores a et laudantium consequuntur. Eos dolorem sunt quia asperiores.', 'Odit quaerat quis suscipit temporibus. Sint libero corrupti impedit nostrum a. Est alias totam laudantium nihil esse libero corrupti odit. Id recusandae corporis animi adipisci sit praesentium et.', NULL, 9701861, '2018-05-24 17:06:10', '1994-08-18 02:01:58')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (24, 'Omnis nisi molestias labore maxime nemo eos. Ut et atque harum. Sed quod eaque id aut et omnis. Et non nihil perferendis ea ut velit aut exercitationem.', 'Unde nam nihil corporis nobis corrupti assumenda molestias sed. Explicabo necessitatibus reprehenderit impedit quo. Quo eos ratione illo totam. Quasi rem et nemo hic excepturi et.', 'Impedit soluta in aut et id dolor. Modi quis omnis incidunt alias sed tempora ut. Sequi inventore qui cupiditate ea voluptatum sit. Dicta delectus accusamus laborum quia aut ullam voluptatem.', NULL, 8682, '2019-05-24 00:15:26', '2017-04-09 06:21:10')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (25, 'Architecto aspernatur velit nisi autem. Quis earum sit veritatis est et. Voluptas sed sit voluptatem porro. Sunt dolore ipsum repellendus reiciendis omnis.', 'Amet illo fugit corporis. Ut suscipit quas ratione est odio perspiciatis quia. Non quo consectetur vitae aut qui.', 'Est exercitationem eum impedit. Ex omnis sint dolorum laborum sed. Cupiditate et rerum aut incidunt eum. Dolorem vitae culpa velit qui. Illum sint aut itaque id voluptas voluptas.', NULL, 9, '1995-11-12 19:31:41', '1987-09-03 19:16:23')");
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}