<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240723131255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Data migration';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (1, 'Est doloremque ea dolor quos blanditiis dignissimos exercitationem rerum. Autem id possimus voluptatum amet. Dolore officia et architecto eos tenetur. Laborum vel laborum voluptatem aspernatur.', 'Sequi est aut expedita. Accusamus velit et dolorem placeat. Enim molestias alias quasi aspernatur veniam qui. Rerum non libero totam est rerum. Rerum et vel ad esse dolor animi nostrum. Est quia dolorem dolor dolores odit nostrum.', 'Unde sit ut deleniti. Rerum illo qui minima qui nihil officia. A ab est dolor impedit.', NULL, 72130782, '2006-01-20 21:53:37', '2004-05-29 23:21:19')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (2, 'Corrupti exercitationem repellendus consectetur nihil explicabo sunt totam. Aut et qui eos et. Quae aliquid itaque enim sequi. Dolorum quia facere doloremque voluptas minima consequatur nisi. Quae modi amet et est.', 'Ea et minima assumenda eum quam perspiciatis et incidunt. Aut minima cupiditate ducimus recusandae dolores recusandae. Molestiae sit ratione nostrum mollitia sunt fugit. Corporis consequatur qui et nobis.', 'Quia ab ad vitae vitae. Accusantium commodi adipisci similique quis. Voluptas et aperiam rerum nihil reprehenderit. Et molestiae omnis sint dolores facilis deleniti non accusamus.', NULL, 414936572, '1972-02-11 00:45:48', '1970-04-27 05:10:38')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (3, 'Aut mollitia officia cumque delectus nihil. Esse rerum et velit. Reprehenderit pariatur nam voluptate error. Molestiae sint veniam quia asperiores hic temporibus temporibus sunt. Est aut officiis vero ut dignissimos esse et.', 'Quasi autem molestias et nesciunt et illo et sed. Quia voluptatem dolorem tempora omnis ut dicta deserunt dolorem. Qui rerum aperiam exercitationem.', 'Magni non est ut sed ut velit aut. Voluptatum quibusdam est adipisci est corporis aut iusto. Et omnis et neque.', NULL, 8, '1978-09-19 04:17:51', '1995-07-24 02:26:33')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (4, 'Sint minima odio consequatur omnis reprehenderit. Iste in iusto nulla ad. Consequuntur placeat eaque consectetur deserunt. Maiores ratione neque aut. Et odio minus aut iste dolorum tempore veniam.', 'Aspernatur unde molestiae rerum similique eum blanditiis quis dolor. Facilis quia alias accusantium cumque. Sit harum saepe non eligendi labore ut laudantium soluta.', 'Ut quia ut facilis praesentium accusantium omnis. Officia sit magnam hic quis. Molestiae ipsum nesciunt hic nihil earum laudantium saepe.', NULL, 443, '2013-12-19 20:14:25', '2023-10-03 15:46:25')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (5, 'Eius consequatur sit est quo exercitationem iste molestiae. Non voluptates quod consequatur sit dolorem vel. Distinctio soluta sit omnis. Nesciunt enim pariatur perspiciatis praesentium assumenda.', 'Qui aliquid in sequi ut dolores cum. Eaque numquam nihil unde nostrum necessitatibus. Temporibus esse tenetur iusto in ratione labore quo. Tempora qui dolorum consequatur aperiam ipsa voluptatum.', 'Praesentium occaecati rerum temporibus. Explicabo ducimus perspiciatis et maiores occaecati sed dicta sit. Possimus sequi est voluptate reiciendis reprehenderit.', NULL, 68, '2017-11-23 06:17:45', '1990-01-31 01:35:09')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (6, 'Debitis ea fuga est necessitatibus. Veritatis cumque non ut possimus maiores. Officiis reiciendis iusto praesentium facere fugiat assumenda ut. Cupiditate quia in sed qui tempore.', 'Veritatis magni ullam dicta earum veniam. Voluptas dolore illo veritatis unde.', 'Quia dolores dolorem aperiam asperiores. Magni est similique magnam nihil. Atque eaque ut iure ea nobis dolorum exercitationem. Ex et quia quia officia possimus.', NULL, 9, '2019-11-08 08:08:23', '1985-06-12 13:45:34')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (7, 'Vitae soluta eos vel exercitationem labore. Omnis repellat ut corporis et eligendi expedita placeat quia. Sit omnis modi iusto nulla tempora temporibus dolorum.', 'Hic adipisci vel tenetur quibusdam. Recusandae atque voluptas error ipsa et voluptatum. Et quis sed voluptate ullam.', 'Quibusdam non maxime neque. Ullam incidunt quam dolor possimus cumque repellat alias. Nostrum possimus impedit voluptatem adipisci.', NULL, 8435917, '1975-03-08 22:40:01', '2008-05-20 15:07:08')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (8, 'Asperiores alias debitis magni cupiditate totam harum in aut. In rerum repellendus molestiae velit. Non minima aspernatur incidunt rem aperiam ducimus. Porro eos error minus hic.', 'Quia et sed et nihil libero. Vero nobis accusamus impedit nam quis ut. Sed ullam asperiores porro facilis incidunt. Ut voluptatem et quam non tempore est sed aut.', 'Eveniet maxime dolore nihil laboriosam laudantium impedit dolores quae. Omnis vero odio quibusdam aspernatur quam eos ea voluptatibus. Suscipit et autem impedit autem sit non alias.', NULL, 6347, '1989-09-22 14:11:46', '2022-03-05 19:39:55')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (9, 'Dicta velit aut repudiandae repellendus cumque voluptatum molestiae. Qui perspiciatis et quia voluptatem quas sit. Non amet nostrum ducimus saepe omnis.', 'Accusamus et qui delectus minima exercitationem dolorem illo dolor. Voluptates voluptatem sapiente illo vel aut a illum sint. Sapiente sed voluptatem vel necessitatibus et necessitatibus.', 'Optio aut omnis aut ea. Explicabo dolor et praesentium tempore impedit. Totam voluptas praesentium sit dolores laboriosam eos eum hic. Eum porro id quidem repellat explicabo quisquam magni.', NULL, 528668325, '1980-07-14 05:07:33', '1986-01-07 12:02:03')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (10, 'Dolore iure quo ad quas sint commodi. Suscipit similique consequatur voluptatem nisi repellendus minima. Autem optio unde pariatur reiciendis consequatur. Repellat consequatur sint nihil laborum rerum a.', 'Aliquid et voluptatibus est. Neque quisquam qui reprehenderit at et aperiam.', 'Qui tempora sit id et quia. Ut nulla dolores et non. Velit nihil consequuntur maiores aut accusamus nobis consequuntur.', NULL, 901717, '2001-09-22 08:00:29', '2005-10-25 19:30:10')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (11, 'Reiciendis in doloremque sapiente fuga maxime consequatur. Incidunt repellendus delectus et quaerat neque. Debitis a voluptas fugiat deleniti. Dolorum vel numquam quisquam quibusdam officia eius.', 'Rem odio beatae amet dolorem quo dignissimos aut sunt. Voluptates ea maxime exercitationem cum iure facere voluptas. Beatae deserunt ea sunt nihil quaerat fugit. Excepturi odio deserunt omnis eaque unde nihil.', 'Suscipit minus officiis facere. Quia rerum atque voluptatem consequatur. Voluptatibus eaque occaecati perferendis.', NULL, 7669279, '1971-11-30 12:41:23', '1972-11-29 16:32:35')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (12, 'Officiis earum iure quia molestiae. Voluptatibus enim qui sit aperiam molestiae. Eveniet et veniam adipisci exercitationem adipisci ut. Sunt labore ea earum voluptatem qui recusandae similique. Architecto officia et fugiat et qui delectus asperiores et.', 'Quisquam aut facere sapiente velit nesciunt. Nihil autem cum maxime dolor dicta. Aut architecto tempore quisquam et officiis iusto a minima.', 'Soluta ea assumenda consequatur temporibus. Eveniet ut voluptas neque dolorem autem illum eligendi. Aut quasi reprehenderit quisquam aut.', NULL, 13, '2012-06-27 12:22:09', '1978-07-17 06:13:48')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (13, 'Vitae culpa ratione quis et modi aperiam. Non vero dolorum alias dolorem et neque. Aut nostrum maxime aliquid rerum et quia. Voluptates nulla perferendis maiores eos eveniet tempore.', 'Vitae omnis quo qui id et provident eveniet. Culpa vel quibusdam laudantium doloremque rerum. Perspiciatis unde et officiis aspernatur cumque hic qui.', 'Qui unde quas qui nihil porro quo. Accusamus at ad maxime qui. Cupiditate id velit nihil consectetur commodi libero quia.', NULL, 45, '1973-12-19 03:38:02', '2001-10-26 23:30:10')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (14, 'Qui esse et repellendus distinctio dignissimos sunt. Et vel sit odit cum sapiente. Dolor rerum consequatur pariatur harum dignissimos eaque voluptatem.', 'Hic deleniti quia excepturi. Accusantium quaerat dolorem cupiditate deleniti officia adipisci quia unde. Voluptatem voluptatum soluta tempore libero iusto. Deleniti ut libero quas cumque fuga.', 'Consequatur maxime modi placeat fugit quo omnis. Vel aliquid optio ab nihil. Aut cupiditate quas odio.', NULL, 54, '2002-08-10 20:06:32', '2023-02-12 13:16:35')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (15, 'Harum ipsam velit quas. Est sed est quia odit. Rerum praesentium molestiae voluptatum qui. Accusamus voluptas pariatur aut vitae quis.', 'Harum modi sed architecto soluta vel beatae. Molestiae non ipsa dicta ut. Recusandae quos ratione ut labore.', 'Aut rerum et voluptatibus repudiandae itaque minus. Labore praesentium cumque unde.', NULL, 4966, '1979-12-04 19:22:04', '2005-06-07 06:36:27')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (16, 'Rerum officiis ut recusandae est in cupiditate eos. Repellendus laborum rem molestiae eveniet libero aperiam ut. Voluptatibus molestiae non neque iusto quasi.', 'Esse quod occaecati nam. Tempore ut ipsa quo ut molestiae itaque quia. Enim magni atque dolor eum adipisci sapiente.', 'Quis eveniet consequatur dolores ut qui rem error. Ex quaerat reiciendis sint debitis excepturi et eaque. Architecto repellat blanditiis inventore et velit. Ut dolorum voluptas adipisci.', NULL, 922591962, '1970-11-26 01:56:28', '1980-07-11 02:58:01')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (17, 'Blanditiis quo qui voluptas est sint. Vitae soluta reiciendis deleniti in. Consequatur ut non culpa perferendis quia velit nesciunt. Nesciunt temporibus laboriosam libero et animi.', 'Et qui itaque commodi iure dolore hic. Est alias nulla eum dignissimos consequuntur dolorem possimus ex. Ullam minus omnis dolores sint ut sit ipsa nihil. Necessitatibus quod debitis vitae.', 'Aliquid eius fugit facilis quidem voluptatem excepturi. Omnis et nisi est mollitia. Tempore ad possimus nihil accusantium numquam soluta.', NULL, 4466169, '1983-06-15 17:22:18', '1989-02-06 17:03:38')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (18, 'Quasi sit eos voluptatum quas. Tempora est fugit sunt et ut. Accusantium commodi inventore sapiente sed. Impedit perspiciatis quaerat rerum.', 'Mollitia recusandae necessitatibus ratione aut. Amet iure sit facilis et quia. Officiis nihil porro quisquam hic labore ipsam. Quidem quia animi possimus libero voluptatum rerum. Et voluptatem labore cumque deserunt distinctio mollitia.', 'Saepe voluptatibus consequatur saepe. Quo sed impedit eos aliquid dolorum. Eius omnis repellat deserunt occaecati quo optio repellat.', NULL, 789, '2002-02-06 18:55:13', '2007-01-11 23:28:52')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (19, 'Doloremque ut amet reprehenderit. Est sed consectetur modi magni facere. Et modi asperiores odit.', 'Dolorum dolor alias possimus. Facere consectetur aut natus aut doloremque. Qui provident iusto tempora aut molestias.', 'Incidunt omnis eos voluptate voluptas. Optio excepturi nam quae et. Fuga vel odit vitae. Saepe exercitationem non ut dolorem. Dolor consequatur vel quam magnam dolore non non nobis.', NULL, 22122, '2002-04-21 20:13:48', '2020-07-29 14:53:06')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (20, 'Omnis facilis odit et. Est est eveniet maxime et. Aut est sed corporis quia laboriosam qui praesentium.', 'Ducimus et tenetur autem at. Voluptas necessitatibus fuga dicta et asperiores fugit explicabo unde. Quae eos temporibus ipsa est.', 'Facere aut omnis suscipit sit sed ipsum rerum. Molestiae ea est vel et. Aperiam incidunt quisquam et ea fugit suscipit nihil. Officia eos sapiente libero est odit.', NULL, 706941883, '2005-02-22 05:03:31', '1983-02-11 13:49:09')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (21, 'Nihil fuga officia eius aut velit. Quisquam facilis quasi et accusamus. Est delectus esse nam totam sed. Iste placeat quaerat et error libero ducimus in.', 'Est et quo enim ipsum necessitatibus est similique. Ullam vitae nisi perferendis ab reiciendis. Cum nihil assumenda rerum laudantium. Et accusantium soluta nostrum consequuntur est deserunt est. In exercitationem expedita nesciunt provident.', 'Voluptas tenetur iusto repellat. Est ratione sit vel adipisci. Inventore praesentium pariatur ipsa nostrum. Eaque corporis sit assumenda et dicta eaque recusandae quisquam.', NULL, 9469, '2003-01-30 17:33:15', '1998-12-02 15:02:16')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (22, 'Perferendis repellendus quo dolores cum tempora et. Sapiente sapiente suscipit aut. Ex voluptas corrupti incidunt accusamus amet sit. Sed facere officiis blanditiis unde consequuntur porro in perferendis.', 'Dolores veritatis commodi sed repellat dolor beatae quasi. In enim tempore aut qui officia. Necessitatibus sint incidunt unde nobis. Aspernatur eaque aperiam voluptatem sapiente.', 'In nihil quod quisquam ea dolores praesentium. Omnis impedit animi non aliquam. Reiciendis odio totam excepturi. Odio aut exercitationem hic dolores voluptatibus. Officia reprehenderit dolor cumque.', NULL, 29901, '1975-06-08 14:39:37', '2006-04-17 23:14:05')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (23, 'Exercitationem expedita provident odio dolorem ullam. Laudantium alias adipisci corporis. Sint velit dolores adipisci minus et voluptas officiis.', 'Quam laborum nihil earum cumque dolores. Rerum molestiae hic suscipit aliquid. Suscipit sint explicabo corporis asperiores eius debitis.', 'Libero deserunt delectus est recusandae. Dolorem labore repellendus aut. Voluptatem excepturi molestias ut ea.', NULL, 0, '1981-07-13 23:06:10', '1980-11-28 11:38:24')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (24, 'Eveniet facere quidem velit. Aut dolores aliquid totam animi. Qui et quo dolores. Nihil iusto consequatur hic.', 'Ratione reprehenderit autem ut facilis. Enim aut non omnis quidem commodi. Iusto facilis quaerat ducimus provident. Aut vel deserunt culpa corrupti hic voluptate qui.', 'Nemo dolores rem corrupti magnam mollitia. Officia nisi et nesciunt odio ut molestiae.', NULL, 777927591, '1994-05-04 19:41:12', '1991-07-21 05:48:45')");
        $this->addSql("INSERT INTO question (id, name, slug, question, asked_at, votes, created_at, updated_at) VALUES (25, 'Dolor aperiam fugiat labore itaque at laboriosam impedit quia. Et consequatur perspiciatis sequi eum dolores corrupti. Ipsa dolores autem odit et sit rerum aliquid at.', 'Dolore fuga molestiae dolorem rerum assumenda. Ea est enim eaque mollitia. Ratione molestiae id ut. Voluptates perspiciatis sequi perspiciatis exercitationem blanditiis ipsam sint ut. Ratione et dolorum nam.', 'Quaerat dolores dignissimos consequatur provident sit. Esse eaque blanditiis nemo. Maiores non deserunt adipisci aut odio occaecati blanditiis animi. Saepe sunt id ut esse.', NULL, 373158697, '1992-05-07 10:10:48', '2020-10-24 01:13:46')");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (1, 'Minima ipsa provident voluptas nisi non maiores nihil sed. Animi aut molestiae nulla facilis. Rem sed eos quisquam alias quis asperiores ducimus. Amet saepe rem consequatur occaecati id natus minima.', 'Inventore rerum voluptate doloremque cupiditate tenetur minus. Eos eaque earum rerum facere expedita deserunt nesciunt. In aliquid suscipit doloribus asperiores corporis reprehenderit. Delectus magni qui in veniam.', 478097, '2015-08-16 08:49:39', '1992-03-07 10:15:58', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (2, 'Qui omnis deserunt dignissimos aut tempore. Sapiente non ullam eos iste est. Ut saepe nisi hic inventore. Ullam voluptatibus quis magni et est in pariatur et.', 'Itaque nam consequatur dicta non deserunt at. Voluptatibus ut sit est et nobis cumque. Laudantium nulla modi tenetur natus. In nihil hic est ipsum ullam.', 362, '2016-03-24 02:55:58', '2000-12-20 20:36:40', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (3, 'Quo aut natus ut. Possimus dicta et sed nam voluptas provident. Est suscipit suscipit inventore nesciunt aut quasi aut. Assumenda omnis rerum tempore molestiae temporibus tempora perferendis.', 'Consequatur eveniet qui suscipit. Neque quaerat harum in. Consequatur eligendi sed commodi et et asperiores. Mollitia voluptate animi ullam et maiores necessitatibus.', 0, '1986-10-11 20:46:44', '1979-03-06 16:26:19', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (4, 'Ut accusantium fugit laborum quis id consequatur. Unde velit eos ea assumenda illo. Ducimus ea dicta neque debitis ipsa ut dicta. Sapiente aut ad culpa repellendus repellendus quos est placeat.', 'Accusantium repudiandae eius nemo. Omnis maxime veritatis dolorem accusamus voluptatum aut. Quia est minus et labore. At praesentium numquam iure et neque. Accusantium officia dolore quia minima magni.', 40482, '1987-07-26 07:52:17', '2002-03-01 08:46:03', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (5, 'Ipsam sed illo nihil id quo voluptatem. Mollitia ad tempora voluptatum ab eaque repellendus non. Aut consequuntur dolorem est vitae.', 'Non nostrum eligendi blanditiis saepe. Eos sint aut quia tenetur. Qui quia quaerat vel culpa debitis a. Sunt quasi ipsa et ipsa voluptatum quaerat quidem. Animi voluptatem assumenda quibusdam cumque ex vel ratione. Modi ipsa neque in amet quas rem.', 779, '1996-08-04 17:26:44', '1980-12-26 16:28:24', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (6, 'Autem nemo recusandae quis cumque temporibus quo consectetur. Doloribus aliquam veritatis ratione neque quasi voluptates velit. Perspiciatis aliquam labore aut officiis aperiam dolores.', 'Et harum sint reiciendis voluptatibus fugit. Iste minima nostrum laborum ut. Sint aut et omnis facilis. Repellendus fugit earum aut magnam voluptatibus cupiditate reiciendis.', 624471, '2002-12-31 19:58:15', '1999-09-30 01:57:48', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (7, 'Quia necessitatibus ipsam illum quia. Culpa iure qui aliquam incidunt. Rem modi in sit repellendus. Vitae et deleniti cumque officia dicta porro.', 'Enim mollitia placeat placeat. Omnis recusandae voluptatum laborum beatae. Sed deleniti itaque modi vel.', 392105, '1980-02-06 05:36:27', '1998-08-27 23:51:09', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (8, 'Doloremque quis sint quis deleniti dolorum ad fuga perferendis. Ut voluptate ut et. Et in error doloremque illo. Dolor qui rerum voluptatem voluptatem voluptatem ut error.', 'Consequuntur expedita eligendi animi et. Perferendis sequi odit sunt necessitatibus ducimus eius mollitia. Doloremque sit voluptatem excepturi voluptas eum at cupiditate ut. Nihil similique ullam sequi vero eum beatae alias.', 8461, '2017-04-17 08:31:35', '1976-02-20 12:31:28', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (9, 'Qui voluptatem molestias rem reprehenderit aut pariatur rerum. Aperiam sed doloribus a mollitia maiores inventore et ducimus.', 'Aut consequuntur quaerat quod id. Amet nihil commodi repellat vel impedit quisquam quis a. Repellat omnis ut ut.', 2920291, '1999-11-16 00:48:43', '1970-01-14 22:37:15', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (10, 'Blanditiis perspiciatis deserunt totam voluptates veritatis. Ipsum et ut et sapiente facilis molestiae necessitatibus. Aut non recusandae dolore.', 'Alias nostrum cum nostrum optio. Voluptatem maxime sit magni eaque quia labore. Veritatis debitis expedita expedita vel aperiam. Aliquid beatae iusto tempora consequuntur excepturi cupiditate nihil.', 10205570, '1970-10-31 22:38:55', '1986-02-11 10:41:58', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (11, 'Qui eaque aut voluptas praesentium rerum illum similique neque. Et molestiae inventore eligendi voluptatum. Et iste tempora velit recusandae. Iure vitae sed suscipit fuga aut asperiores voluptatum.', 'Consequatur dolorem occaecati rerum molestiae libero laborum corporis. Debitis itaque placeat eos voluptatum aut corporis.', 57523409, '1974-11-24 10:22:53', '1989-03-24 19:01:40', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (12, 'Tempora dolore dolore eos sunt. Possimus incidunt voluptatem explicabo voluptate. Quidem quia ut minus temporibus repudiandae. Est iure libero et et dolores quia.', 'Cumque sunt distinctio eius ullam excepturi cupiditate. Quibusdam placeat qui qui qui ea. Ratione ut dolorem accusantium saepe cumque. Dolor qui quisquam accusamus beatae.', 5872372, '1990-06-28 03:29:42', '1970-12-03 04:00:44', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (13, 'Aperiam possimus a assumenda. Cumque aut porro in iusto sint. A nihil ea voluptatem corrupti.', 'Est eos non occaecati aspernatur ullam non adipisci. Optio rerum quis eaque. Maxime quaerat sed earum. Ipsam et nostrum veniam fugiat eos. Et est quod rerum nobis atque.', 203, '1993-10-18 09:26:09', '2020-04-23 00:11:35', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (14, 'Aut numquam unde atque laboriosam mollitia animi. Qui enim autem eos qui quod. Culpa dolor pariatur enim eum neque dolores at.', 'Aut reprehenderit officia aut id ea perspiciatis ullam. Molestiae aut quibusdam sequi. Voluptas consequatur debitis asperiores dolorum nulla nisi.', 47949, '2012-11-07 06:07:39', '1980-03-03 07:07:49', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (15, 'Laudantium reiciendis velit voluptatum numquam ut. Et porro perferendis commodi quo ipsam maxime error.', 'Laudantium quo impedit corporis aliquid voluptatem earum. Architecto quis dicta beatae laboriosam sint tempora. Rerum quia vitae fugiat ipsa. Similique aliquid occaecati eius a ex fugiat. Doloribus eaque ex et non. Voluptas laudantium eos et ut.', 56172008, '2011-06-21 07:40:22', '2002-04-02 23:44:31', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (16, 'Perspiciatis eligendi nobis aut nobis dicta. Et totam dolorum occaecati minima dolor. Dolorum qui vero qui aliquid.', 'Fugit voluptate nostrum libero distinctio. Quia recusandae iure praesentium distinctio ut quia. Voluptates animi sed ducimus sint quia quia.', 342, '1991-03-22 15:28:01', '1973-11-07 02:49:39', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (17, 'Quia nisi sint quis vitae illo officiis quibusdam. Adipisci debitis nihil maxime odit provident modi quia. Sapiente consequatur velit dicta aliquam. At et veritatis voluptatem voluptatem aut.', 'Quo mollitia eius tempore rerum molestiae omnis ipsa. Fugiat et hic et quae vitae. Quis nihil qui tenetur dolore qui. Nam labore vitae culpa eum laborum eum.', 9128804, '1988-06-10 21:55:48', '1996-11-03 07:18:20', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (18, 'Similique ut vero qui voluptas debitis est ut. Aut pariatur ea ea. Libero voluptatum dolores quis distinctio asperiores.', 'Modi non expedita incidunt. Ab ipsa quo eligendi ut.', 9, '1979-11-23 19:13:59', '1980-09-23 05:31:52', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (19, 'Quaerat eveniet sunt architecto dolor officiis. Asperiores est accusantium non architecto vel consequuntur. Est qui molestiae aut commodi natus maxime. Minima explicabo non beatae quia corrupti.', 'Sed beatae officiis explicabo reiciendis quod rerum provident. Perferendis quisquam nihil doloremque. Sunt recusandae earum cumque nam.', 299, '1974-08-04 09:08:39', '2019-09-30 16:02:26', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (20, 'Vel quis cumque asperiores consequatur. Necessitatibus dolor officia cupiditate et consequatur. Totam ratione consequuntur tenetur a ad ipsum aut. Voluptas maiores dolores voluptatem.', 'Et excepturi adipisci fugit optio. Ad sit voluptatem eius ab. Aut quod ut sed perspiciatis in. Laboriosam id cumque magnam modi quod.', 128332, '2019-03-05 18:27:15', '1970-11-15 02:17:49', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (21, 'Ab cumque voluptas accusamus molestias. Sunt tenetur ex et nihil est eos. Quis velit non nostrum voluptate omnis. Velit voluptates consequatur aut est eos soluta et.', 'Dolorem dolorem aliquam quos unde et ab. Enim cumque et molestiae minima qui. Ullam corporis qui dolores sed modi repellat nam ut. Velit est nihil debitis blanditiis doloribus.', 66623, '2017-04-02 18:56:59', '1999-08-21 15:53:59', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (22, 'Corrupti ea provident earum delectus autem quisquam atque. Dolor maiores voluptatem ullam sit. Laborum rerum qui quas atque. Distinctio quod dolores dolorem.', 'Fugit rerum aliquam vitae similique veritatis et. Quia recusandae praesentium sequi sit cupiditate porro aut. Maiores facere aperiam iusto explicabo pariatur eos molestiae.', 746579680, '2021-09-08 11:50:48', '2003-07-21 23:56:39', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (23, 'Quaerat dolores quaerat laborum. Dignissimos excepturi a blanditiis consequatur officiis magnam. Est eum nam et enim quis expedita.', 'Et porro molestiae veritatis facilis repellendus sed iure. Ex illo quia voluptas provident quae. Provident ut soluta asperiores non.', 69202, '1976-01-06 08:39:43', '2013-07-08 14:36:23', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (24, 'Architecto quia ut autem nobis aperiam. Inventore ex magni nemo animi. Ipsum labore recusandae dolorem aliquam aut expedita. Et autem laudantium libero dolor.', 'Dolor quia non ut culpa nobis atque est. At autem qui fuga aut officia soluta quia. Unde quis mollitia ut quidem reprehenderit quo. Rerum ipsa voluptatem earum unde sunt. Occaecati dolor unde et ipsam dolores ut quia. Officia laboriosam rem ad similique.', 5, '2015-09-27 01:11:09', '2000-07-13 15:07:30', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (25, 'Exercitationem molestiae sit doloribus nihil eos. Id nihil natus deserunt quam. Et qui vel velit quia non. Error atque odio dolor tenetur consequatur. Sit illum et harum est quibusdam.', 'Deserunt architecto est veritatis laborum. Accusantium sapiente aut maiores et optio neque aut. Possimus labore voluptate vel sint veniam quasi.', 50669, '2008-06-16 05:15:36', '2013-07-28 18:49:23', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (26, 'Rerum dolores recusandae repudiandae recusandae. Minus non velit magni. Dolor commodi minus cumque et rem modi reprehenderit ut. Et expedita autem deserunt fugiat quidem quaerat.', 'Est voluptas eaque aut magni. Quas aut occaecati est itaque. Exercitationem amet aliquid magni accusamus suscipit rerum maiores ut.', 8967, '2022-08-23 06:55:21', '2002-01-29 09:21:42', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (27, 'Sed esse vel explicabo. Vel porro suscipit commodi sunt iste. Similique tenetur quos praesentium dolor commodi dicta. Eos sequi et iste et omnis natus ut. Quia enim et inventore nihil et est.', 'Et placeat amet voluptate quod incidunt nisi. Sunt magni facere ut numquam quis. Dolor et excepturi omnis odit mollitia illum inventore. Consectetur alias et sit in inventore unde.', 767, '1977-08-21 02:28:28', '2015-07-26 18:13:48', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (28, 'Nemo enim qui sit corrupti illo. Consequatur omnis blanditiis blanditiis distinctio. Dolorum quis eum enim facilis assumenda dolor.', 'Quis quia iure assumenda maxime molestias eos. Et qui non rerum temporibus aliquam ratione. Non quidem quia est laboriosam.', 2, '2001-09-16 19:23:12', '1977-08-27 10:24:20', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (29, 'Excepturi est odio autem ut repudiandae. Suscipit maxime quia voluptatem omnis. Voluptatem enim ut enim quisquam in. Porro et quis omnis iusto.', 'Enim sint non natus maxime quos est. Vero aut minus voluptate. Laboriosam voluptas distinctio eligendi ex tempora.', 5, '1995-12-08 15:34:40', '1992-01-04 15:45:53', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (30, 'Non nesciunt omnis in ab illum soluta. Alias doloremque quia unde aliquam. Quis ut eligendi autem aut quam. Sit voluptates perferendis ea fugit neque nam.', 'Temporibus sed vero maxime nulla distinctio natus. At rerum laborum quos voluptatem. A officiis veritatis non quia et ut sunt quia. Consequatur porro officia neque ipsum laboriosam eum.', 303965198, '1973-09-22 02:09:59', '1993-11-22 16:32:20', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (31, 'Veritatis facilis vel voluptatibus dolores. Quibusdam similique quidem dignissimos. Rerum ea at voluptatem.', 'Mollitia est repellendus vero eum praesentium. Eum est odio quia atque. Tempore quasi minus perferendis dolore officiis minima veritatis accusamus. Sunt sit rerum magni tenetur neque praesentium.', 390071818, '2004-03-25 21:07:35', '1996-03-01 03:57:19', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (32, 'Repellendus in voluptas dolores vel eaque ducimus. Nulla voluptates eos architecto illo qui aperiam corporis. Molestiae ex debitis eius.', 'Dolor recusandae doloremque velit. A distinctio nulla consectetur provident atque. Qui velit rerum laborum voluptatum repudiandae commodi temporibus. Qui et aliquid in voluptas sunt.', 711, '2004-09-16 03:20:22', '1993-10-08 08:08:45', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (33, 'Corporis eius iure eligendi. Itaque numquam voluptatem ut et ut impedit. Porro soluta soluta quisquam unde consectetur nihil aut magnam.', 'Tenetur quaerat ab dolorem quo ut quae mollitia tenetur. Itaque non quas ipsa. Qui sed aut modi non est.', 43933, '2003-05-18 19:35:53', '1971-02-28 00:33:16', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (34, 'Placeat velit dolor amet. Aut maiores eum ut consequatur voluptatum. Ea ipsam illum molestiae sit quisquam. Qui eius doloribus mollitia dignissimos molestiae voluptates aliquid.', 'Praesentium facere magni ipsum quod. Animi voluptas fugiat recusandae qui et. Iusto eius assumenda nobis accusantium rem. Et laboriosam aliquam iusto at tempora est in.', 6, '2013-07-07 18:17:01', '2017-04-13 02:15:10', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (35, 'Non sunt et cum molestiae. Et ut beatae iure. Rem similique similique non ipsa mollitia quia. Vel a nostrum porro sint.', 'Quo quia et dicta ad autem voluptas expedita adipisci. Ut odit nisi et sint similique laudantium asperiores veniam. Quis deserunt eligendi quo odit eum maiores. Sed autem dignissimos enim vel explicabo dolores.', 670217, '2016-12-27 08:50:28', '2003-01-28 19:18:11', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (36, 'Ullam qui possimus temporibus omnis. Aut omnis expedita et vel rerum. Iusto perferendis aperiam eius voluptatem. Sit delectus quis sequi voluptas numquam corrupti.', 'Vel omnis consectetur voluptatem laudantium autem adipisci consequatur. Aut quibusdam pariatur expedita dolorum magnam quis. Odio dolorum et velit hic numquam.', 57164712, '2007-09-19 14:35:33', '1977-09-23 05:41:01', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (37, 'Aliquid quidem quam quisquam eius inventore id consectetur. Et ut delectus velit nostrum. Neque harum aut ut. Voluptas minima quia corporis ut commodi quidem laboriosam.', 'Explicabo id ut eum occaecati at autem. Facilis ad ullam quia perspiciatis. Eaque magni ut ipsum perspiciatis. Repellendus voluptatem eos dolores sint. Ut veritatis amet a sapiente necessitatibus impedit consectetur. Dolorem vel assumenda eum.', 66, '2021-02-19 18:43:26', '2007-04-15 22:47:56', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (38, 'Totam quas error aut odio porro cumque quia aperiam. Sit eius officia itaque in nam sint quidem. Deserunt a nihil praesentium inventore.', 'Consequuntur occaecati ipsa quod tempora adipisci voluptates. Quidem possimus quia velit. Nobis facere maiores commodi fugiat voluptatem.', 8797043, '2013-10-26 04:41:18', '1982-09-22 21:05:25', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (39, 'Voluptas eos et natus rerum est assumenda. Non nesciunt quae rerum omnis. Voluptatem doloremque delectus repudiandae perspiciatis aut explicabo.', 'Labore impedit totam doloribus magni quasi eum soluta amet. Esse iure aut minima quo ut. Quod ab ducimus at ipsa id et porro. Sint quibusdam quis voluptate.', 6755, '2021-03-01 10:33:15', '1999-02-08 22:21:04', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (40, 'Officia ut assumenda cupiditate accusantium maxime. Recusandae ipsam omnis aut quis harum eos.', 'Perferendis nihil dolor odit dolorum qui hic ut. Natus cupiditate nobis eligendi nihil. Quis libero impedit et delectus architecto labore.', 642115, '1972-09-05 06:48:45', '2013-12-21 20:05:15', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (41, 'Eaque itaque quae assumenda veniam. Natus atque sunt tempore id ipsa nam vel ut. Temporibus laborum maiores necessitatibus adipisci maiores et.', 'Modi inventore consequatur illo eum. Sunt deserunt voluptas laboriosam fugit porro aut eum. Mollitia alias numquam repellat id magni a et. Consequatur in molestiae iste facilis inventore excepturi. Fugiat et et dolor ea.', 907391792, '2017-05-12 09:56:08', '2009-06-25 17:39:11', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (42, 'Non voluptas aut nisi molestias sed ipsam perspiciatis. Placeat omnis laboriosam dolorum sit magni eveniet blanditiis eius. Nostrum quos rerum quis eos. Facere aut sed enim consequatur est.', 'Corrupti ea in doloremque et. At ex hic incidunt qui tempore est. Et itaque sed quaerat iure. Nihil occaecati non voluptatem eveniet.', 4855, '2021-03-12 00:05:32', '1997-03-08 02:30:21', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (43, 'Sed qui sequi ullam sed exercitationem voluptates. Ab est omnis aperiam culpa voluptate doloribus. Culpa est est est qui maxime voluptates qui. Ab quo nihil soluta minus.', 'Est ipsa ipsa consequuntur dolorem non. Architecto nihil ullam quis rerum rerum deleniti beatae. Pariatur quia nihil et eligendi. Aut aperiam velit velit saepe aut voluptas. Voluptas a fuga repellendus dolor nulla. Fugit eius consequatur facilis odit.', 7359708, '2023-08-29 13:00:05', '1999-02-11 09:45:19', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (44, 'Amet repudiandae quibusdam eligendi dolorum et ut eos. Quaerat laborum nobis quia error. Dolores sequi velit architecto ullam eum aperiam sed.', 'Ut quia pariatur assumenda odit quod ratione. Quod vitae id maxime. Consequuntur sed eum autem asperiores. Suscipit non rerum ipsa adipisci porro fugiat. Veritatis facilis ut tenetur. Dolorem quia vitae incidunt. Ipsum sit nisi id rerum eum culpa.', 522854, '1982-01-31 02:12:59', '1982-03-19 06:29:25', 17)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (45, 'Recusandae ut cum velit repudiandae quasi magni et ut. Veritatis quis temporibus sapiente. Accusamus non amet non ab delectus pariatur. Enim nisi earum soluta laborum.', 'Porro aliquid sit quam est ut qui adipisci. Iure voluptatem ducimus dolore earum. Magnam voluptate provident et. Ut quis ab soluta dolor. Sint eveniet beatae eum aut.', 5946839, '2007-11-15 17:56:00', '1996-10-05 02:20:22', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (46, 'Labore temporibus explicabo earum atque excepturi. Quae ut cupiditate et sed ullam placeat ex. Ratione illo voluptates sit qui. Totam veniam nulla maiores sapiente.', 'Asperiores omnis blanditiis dolorem voluptates quae voluptate assumenda exercitationem. Qui et perspiciatis aut consequatur. Temporibus et hic dolores consectetur tempore.', 82, '2000-12-16 22:03:11', '2021-12-09 10:03:56', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (47, 'Odio natus qui laboriosam ea nihil suscipit consectetur voluptas. Beatae eligendi natus nisi sit. Voluptatem harum perspiciatis architecto. Optio quis commodi ipsum eos recusandae voluptas.', 'Sed sequi nulla id debitis illo quisquam aut. Quod voluptatem non velit et. Sit quae distinctio aut nulla dicta harum. Accusantium fugit illum est velit quod earum. Excepturi quaerat ratione delectus ut minima itaque. Laborum repellendus non architecto.', 144, '2005-04-01 21:29:10', '1988-05-15 23:59:34', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (48, 'Sunt esse vitae officiis ipsum quis rem. Ut quo quae laboriosam culpa neque. Fuga placeat sit beatae.', 'Corrupti et nisi ullam aut natus. Eos mollitia est et rerum culpa. Laborum dolorum dolorem et. Culpa natus vel dolores autem molestiae unde accusantium.', 30962660, '1972-11-16 04:18:07', '1983-10-19 13:13:42', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (49, 'Impedit quis aut sequi. Aliquid quas dolore qui maxime. Dolores voluptatum voluptates aut esse.', 'Fugit provident sit et. Qui aliquam a aspernatur voluptas consectetur fuga. Et dolor est fugit vitae.', 763, '2008-02-29 21:57:43', '1992-10-20 01:50:06', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (50, 'Fugiat placeat unde ipsam dignissimos quis id ut. Voluptas id rerum delectus eum aliquid. Aspernatur rerum atque voluptates est. Nihil iure similique a adipisci neque ratione.', 'Quae odit rem praesentium quam rerum quaerat. Consectetur modi esse et quis ut aut blanditiis eveniet. Dicta ea veritatis optio sint accusamus inventore. Placeat praesentium natus autem possimus et.', 29404779, '1998-06-24 13:00:42', '1998-10-10 15:56:15', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (51, 'Magni nihil tenetur quis est. Omnis sed et ullam provident. Nisi animi cupiditate illum eius unde. Qui odio ad nemo culpa eveniet deleniti eius.', 'Quia ullam dolores placeat impedit exercitationem non. Autem velit voluptates commodi eius illo qui. Delectus quidem aspernatur qui animi nam architecto.', 6618196, '2010-12-15 10:33:51', '1991-08-26 22:01:08', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (52, 'Ab necessitatibus et accusantium et est aut libero. Et nobis qui nemo necessitatibus. Quidem nulla quo aspernatur velit consequatur et. Architecto nesciunt praesentium ut voluptatem.', 'Quasi exercitationem hic non ipsum atque. Voluptate velit aut quos dolor consequatur quaerat. Aspernatur doloribus sit incidunt eligendi. Mollitia et et voluptate distinctio aut tempora commodi.', 4834356, '2023-01-26 00:09:16', '1972-03-04 12:23:55', 12)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (53, 'Qui nihil natus nulla ut voluptas ratione. Quaerat beatae sunt animi odit ut voluptates accusamus. Nam reprehenderit accusamus aut cumque. Explicabo voluptatibus occaecati modi dolorem qui enim.', 'Veniam eaque consectetur minima nihil. Qui sit accusantium aut suscipit. Dolorum debitis fuga velit. Quam est facilis ullam qui et et sapiente hic.', 3783684, '1997-11-20 10:34:26', '1980-08-13 21:31:50', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (54, 'Non soluta expedita et dolores occaecati sint soluta. Illo qui reiciendis beatae reiciendis assumenda dicta. Qui voluptate sequi nam hic ea possimus ut possimus.', 'Omnis qui a deserunt quia. Praesentium ipsum quos placeat animi velit. Perferendis sint facere qui adipisci culpa nesciunt. Sint a nisi quasi porro suscipit.', 38, '2017-10-28 13:19:07', '1998-07-15 02:53:26', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (55, 'Iste ullam earum atque inventore aut. Hic recusandae ad et provident aspernatur. Consequatur dignissimos est vel reprehenderit aut autem dignissimos. Eum quas repellat et quos neque sit ut.', 'Dolorum ut aut sapiente pariatur est. Velit sunt occaecati qui totam quod. Occaecati dicta quos soluta beatae quasi aut sunt.', 70149, '1998-04-09 20:31:57', '1978-12-15 01:56:02', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (56, 'Dolorem quis ipsum veritatis recusandae. Facere voluptatem non ut delectus maxime sit molestiae. Corporis a aspernatur est placeat. Hic odio ea officia sed. Et sit autem voluptatum excepturi ut.', 'Nulla iure quisquam est aut facere voluptatibus. Facere earum architecto autem quia natus. Beatae id occaecati nesciunt aliquid cupiditate amet. Et optio et hic qui. Est enim voluptate nihil ducimus. Atque qui laboriosam magni ea.', 137308798, '2013-08-05 00:27:00', '2017-07-31 04:58:20', 10)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (57, 'Libero nobis quae sequi ipsa aliquam nam voluptatem. Ut tempora expedita sapiente tenetur. Magni aut iste alias omnis voluptatem. Laborum soluta asperiores id non culpa et error.', 'Beatae assumenda dolorum odit expedita sunt quis vel. Eligendi maxime sequi vel quibusdam unde similique. Qui earum enim voluptatibus magni.', 1529, '2011-03-21 12:07:56', '1973-01-06 04:11:29', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (58, 'Libero minus qui laboriosam id nobis molestiae delectus. Quod molestias eius hic maxime. Accusantium cumque facilis et corporis qui. Facere debitis nam et accusamus minus ratione.', 'Esse officia dolor et qui corporis sint ex eum. Ad harum minima nulla officiis sit. Repudiandae repellat sapiente sed ratione enim dolor.', 6, '1972-07-24 20:05:22', '1979-07-16 12:58:55', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (59, 'Qui autem magni nemo voluptates. Sapiente suscipit libero explicabo eum quo. Quis ea commodi temporibus quia mollitia. Fuga architecto quia temporibus eos deserunt error.', 'Velit velit voluptatem deserunt qui nobis cum. Ducimus ipsum a inventore quibusdam amet officia. Maiores vel quidem fuga ut itaque nam ea.', 455, '1986-01-19 07:29:17', '1996-12-31 02:01:46', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (60, 'Eligendi autem deleniti sunt vitae omnis molestias. Et aperiam dolor neque officia. Explicabo nam qui ex architecto pariatur. Voluptas optio architecto distinctio sunt suscipit eos nobis.', 'Deleniti minima voluptatum aliquam temporibus fuga qui. Illo atque laudantium molestiae illum. Ut sapiente placeat sint itaque architecto consequatur omnis alias.', 105, '2017-10-21 10:22:06', '1986-03-30 04:08:12', 13)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (61, 'Qui sit quas velit facere eum nemo eum illo. Et amet quisquam quaerat. Eveniet nam qui est qui et ut.', 'Voluptates unde doloremque nostrum occaecati. Ad corrupti quos quibusdam et impedit qui. Minima provident omnis dolor. Aperiam excepturi et animi et harum quidem et.', 67748, '2014-11-19 23:30:58', '1989-10-12 15:40:19', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (62, 'Sint quisquam assumenda dolores ut repellat et. Libero et suscipit omnis velit et voluptas ut. Nihil id autem explicabo praesentium doloribus.', 'Eligendi sapiente ipsa ducimus similique. Fuga voluptates eos laborum accusantium ex repudiandae illum architecto.', 8552137, '2012-06-10 04:37:18', '1988-02-24 11:46:40', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (63, 'Autem itaque a itaque. Laboriosam laudantium consequuntur animi. Voluptas ut autem est quidem occaecati.', 'Facere vitae necessitatibus incidunt vel ipsa sunt. Dolores animi aperiam accusantium ab. Necessitatibus ut et officia rerum.', 130, '2020-09-11 08:12:01', '1970-12-11 14:52:25', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (64, 'Quas accusamus eligendi voluptatum consequatur qui. Quidem tenetur omnis id quo. Odit facere sit assumenda omnis quia veritatis.', 'Et voluptas ut reiciendis et officia. Facilis amet reiciendis magnam eum nulla in. Natus id fugit beatae quos nemo ut. Minima voluptates ut minima error. Reprehenderit impedit voluptatibus vel autem quis temporibus.', 314794, '1982-12-15 15:29:43', '1989-06-28 01:55:27', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (65, 'Quia ipsam occaecati earum aspernatur corporis. Id eveniet vel laudantium qui alias facere explicabo dolorem. Doloribus rem error sed amet.', 'Voluptas quis enim nihil aliquam assumenda. Quas unde mollitia non iure fugiat. Inventore nulla et iusto debitis dolorem. Totam neque et est aliquid voluptatem.', 5794, '1972-05-26 09:16:20', '1984-03-14 15:07:52', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (66, 'Possimus odit commodi asperiores possimus nulla quo harum est. Sed asperiores sit natus iure. Debitis tenetur in aliquam minus iusto aliquid qui et. Maxime iusto voluptate earum aliquam autem.', 'Aspernatur tempore accusantium qui sit sit. Blanditiis quis et quia id hic. Cum qui tempora autem enim.', 93136, '1977-11-24 14:47:24', '1970-05-30 23:27:31', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (67, 'Iste atque dolorum culpa sint soluta. Consequatur enim ut facilis tempore cupiditate error dolorem. Qui et impedit fuga praesentium eius. Asperiores nulla ad voluptatem laborum sit harum.', 'Deserunt praesentium voluptas dolor aut numquam. Laudantium rerum labore dolor nam asperiores. Numquam incidunt repudiandae nesciunt enim. Inventore quis voluptas cum. Eveniet ipsa odio reiciendis sed earum eos voluptas.', 113889156, '1991-05-05 05:59:08', '2018-05-27 03:45:07', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (68, 'Et et quasi autem voluptatem. Nesciunt vitae vel omnis sit accusantium veritatis. Quis illum quia aut esse est vel. Voluptatum et perferendis ut tenetur.', 'Et maxime velit ut. Quaerat qui enim ut consequatur culpa quis. Blanditiis minima culpa veritatis voluptatem nihil. Quidem consequatur sit odio ratione qui repudiandae facere.', 583, '1974-09-22 23:00:47', '1976-12-04 17:25:20', 11)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (69, 'Corporis mollitia sed occaecati maxime. Beatae reprehenderit nobis sunt. Quis expedita ducimus aut et voluptatem reprehenderit eos.', 'Reprehenderit ea non et consequatur vitae. Voluptates distinctio totam sequi ea at error. Perspiciatis enim explicabo repellat enim qui et enim. Libero beatae possimus adipisci nostrum maxime.', 37, '2023-04-04 14:23:59', '2017-01-03 09:43:38', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (70, 'Consectetur qui ad ut consequatur voluptatem. Quidem ipsum dolor nam eaque quas molestiae. Vel qui ut explicabo laudantium fugiat. Tempora impedit rem et doloremque deleniti.', 'Voluptatibus officiis ad rerum aspernatur perspiciatis officiis corrupti. Deleniti vero eveniet corrupti aut repellendus iusto aut. Temporibus non doloremque et temporibus ducimus quasi est. Quos ratione alias magni totam.', 336701, '1996-07-24 00:44:49', '2007-08-25 06:08:34', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (71, 'Minus molestiae nihil a dicta aliquid aliquam. Voluptatem atque iste et soluta recusandae nesciunt ut dolorem. Quis aut est ut fuga ea. Eos laboriosam iste ut.', 'Esse repellat molestiae quo aut quo hic quis. Delectus quisquam minima assumenda vero. Odit ad sapiente tempora vel aut.', 7044426, '1979-06-11 09:42:16', '2020-08-07 12:50:24', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (72, 'Magni ut animi maiores maiores doloremque. Nemo quis voluptatem optio perspiciatis. Praesentium praesentium nihil consequuntur velit ducimus. Illum nemo consectetur ea recusandae.', 'Consequatur quo ducimus ad dicta. Sint quam cumque facere doloribus. Minus odit consequuntur consequatur voluptas laudantium. Repellendus consequatur vitae minus molestiae.', 91814859, '1992-04-16 01:57:02', '1978-09-29 00:50:56', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (73, 'Non qui quia dolores temporibus. Voluptas harum nobis deserunt quaerat. Autem ea animi et omnis quas. Quod quod et nulla.', 'Quidem nam et aut. Doloribus fugiat odit distinctio sapiente aut quam dolore. Ut quod exercitationem enim molestias vel voluptas et aut.', 4954, '1986-11-16 03:49:15', '1996-10-24 02:20:28', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (74, 'Accusamus explicabo maxime et consequatur. Sint natus dolorem rem neque et distinctio dolorum. Amet consectetur illum qui eveniet ab. Voluptatem suscipit blanditiis et sit ea laboriosam aut.', 'Laboriosam omnis quas repellat deleniti asperiores labore rem. At quia totam molestiae omnis asperiores autem nihil. Sint amet laborum iure. Et nisi dolorem molestiae quod. Quia officia minima non et voluptas provident sint.', 42488, '2022-10-04 15:06:50', '1993-12-30 21:55:20', 6)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (75, 'Quod aut enim molestiae possimus. Vel esse qui aut aut tenetur. Tempora ipsa ipsa rerum perferendis quam recusandae minima eveniet. Enim et vero nisi omnis quo.', 'Blanditiis ut sed qui voluptas consequatur itaque assumenda quod. Adipisci explicabo qui aut. Voluptatum magnam illum aliquid suscipit. Voluptas fuga soluta veritatis quae laboriosam. Doloribus est ullam dolore voluptas ipsam.', 4227, '1991-05-27 06:50:51', '1983-09-27 01:47:31', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (76, 'Eaque ducimus et laborum et velit sint. Numquam quo quibusdam a facere et omnis. Architecto sint et iste rerum.', 'Reiciendis et in et ut beatae voluptatem. Numquam dolorum consequuntur provident alias aut velit quo. Et ut incidunt neque officia saepe iste.', 9537, '1996-07-01 10:24:56', '2014-08-12 21:07:45', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (77, 'Repudiandae at quia sint itaque dicta. Facilis sit atque ducimus ea voluptas molestiae et. Dignissimos nihil et necessitatibus rerum tempora minima. Et voluptates nisi atque optio.', 'Rerum inventore dolorum voluptas consequatur est. Excepturi sint nisi ad inventore dolorem ad. Voluptas in totam tenetur similique numquam deleniti.', 9, '1996-03-26 03:37:02', '1972-02-02 14:29:13', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (78, 'Voluptatem a corporis nobis. Est ipsa corrupti qui vel ut nihil. Voluptas reiciendis exercitationem eligendi omnis. Autem quia quibusdam nihil ut ea.', 'Qui cumque sapiente quod quia ut quia veniam. Inventore aspernatur accusamus reiciendis voluptatem magni quia. Debitis culpa dolores qui consequatur.', 27400921, '1972-05-03 21:43:05', '1971-03-01 02:04:49', 9)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (79, 'Odio cupiditate non aliquid perspiciatis. Quia occaecati at ut quos magni. Harum pariatur eaque quia consequatur est est id.', 'Explicabo nobis voluptates repellat eos. Et non nobis cumque et. Aliquid mollitia quia molestiae accusamus. Quidem et excepturi omnis iure incidunt veritatis.', 999587351, '1993-08-07 07:23:09', '1993-11-03 10:48:52', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (80, 'Tempore voluptatum et est sint a rerum dolor aperiam. Nulla quasi in rem alias est et. Qui est ex illo quae odit.', 'Adipisci consequatur qui excepturi. Iusto at odit non ea sed eveniet sapiente quaerat. Fugiat omnis soluta voluptas dolore tenetur inventore. Maiores dolorem molestias autem.', 943724281, '2002-11-01 12:01:17', '2014-07-19 10:00:52', 20)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (81, 'Saepe nobis excepturi odit harum. Repellat et et accusamus. Nulla quibusdam nisi vel reprehenderit est qui accusantium ullam. Quo alias ullam ipsum expedita ducimus omnis et quibusdam.', 'Voluptatem mollitia ipsa ad reiciendis. Consectetur nostrum aperiam provident est impedit quo. Occaecati dignissimos architecto quas reprehenderit modi repellat. Rem est voluptate in culpa deleniti accusantium.', 127003488, '1985-12-11 22:26:44', '1976-12-17 14:34:32', 15)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (82, 'In quidem harum quos perferendis placeat. Eum sed omnis sint veniam sint. Maiores rem voluptatem numquam sit. Reprehenderit quis alias porro repellat qui.', 'Reprehenderit corrupti adipisci aliquam laboriosam et dolores rerum. Ipsa aut qui ut rerum repellendus facere non. Enim nam iure enim voluptate id hic.', 8, '1974-10-14 03:37:58', '1974-02-07 21:50:33', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (83, 'Autem id quas eum tempora. Et et consequatur consectetur quia provident voluptas. Delectus aliquam a aspernatur vero est.', 'Ullam asperiores iste inventore voluptatem quos. Enim aliquam consectetur laudantium sint vel. Omnis rerum assumenda cum veritatis. Maxime consequuntur magnam quisquam.', 1762191, '2008-08-31 08:59:37', '1990-05-06 02:30:26', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (84, 'Exercitationem architecto laboriosam et inventore recusandae. Et hic ea id qui expedita. Optio et ad quidem illo. Ea consequatur alias enim illo.', 'Reprehenderit distinctio voluptas aut temporibus consequatur. Consequatur consequatur consequatur sapiente qui incidunt eveniet nobis. Inventore veritatis deleniti distinctio et et assumenda voluptatem.', 72471, '2003-11-02 10:40:27', '1998-09-10 16:41:32', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (85, 'Debitis sed non corporis. Quo doloremque veniam iure blanditiis dolores. Vitae amet est deleniti eius dolores.', 'Sed repellat molestiae minima non perspiciatis error. Ea sit velit eveniet voluptas officiis est maiores accusantium. Aut ad asperiores laboriosam.', 4788, '1989-02-23 09:30:58', '1984-06-27 19:43:12', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (86, 'Ipsum fuga aliquam sapiente atque libero quis amet. Quis autem beatae qui et. Quaerat nihil eum odit id.', 'Possimus et quam sequi error omnis. Dolor omnis dolorum assumenda ea natus quaerat molestiae. Veritatis sit inventore dolorem quia esse modi consequatur accusantium. Harum enim aut tempore.', 2, '1979-01-24 04:25:39', '2022-12-21 22:42:01', 16)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (87, 'Dolores ipsam eum iste omnis praesentium hic. Aut explicabo non sit illo veniam. Esse sit maxime aut labore quidem expedita aut.', 'Iste voluptatibus pariatur molestias. Dolor est aut quo voluptas. Dolores saepe et omnis necessitatibus quaerat ipsam voluptatibus dolor. Et adipisci molestias possimus harum distinctio. Ullam iusto officiis suscipit et fuga dolore illum.', 626987, '1996-06-14 19:09:58', '2009-06-01 11:02:38', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (88, 'Ea vel ducimus sed. Blanditiis provident natus est officia provident maiores occaecati. Accusantium quia sunt omnis repellat aperiam. Incidunt distinctio minus voluptatum voluptas.', 'Eos a provident corrupti. Exercitationem laboriosam iure voluptatum corporis reprehenderit. Perspiciatis et dolor consectetur voluptatem culpa tempore.', 530539192, '2008-01-20 10:56:13', '2008-05-02 18:34:50', 14)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (89, 'Aliquam est inventore est magni ad omnis voluptatem nobis. Blanditiis voluptatem adipisci molestias dicta nobis. Ut ab et odit voluptatem esse et modi.', 'Eos aut dignissimos fugit labore et odit. Tenetur at officia ipsa veritatis. Omnis quae eius sapiente saepe impedit recusandae magni. Beatae excepturi est dolorem dolores sed minus.', 177847973, '2024-02-23 14:35:36', '2004-09-30 07:08:49', 5)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (90, 'Reprehenderit pariatur rerum non et veniam sit aut delectus. Nisi ut magni temporibus a sapiente ex. Et et atque possimus. Voluptatem aspernatur ea qui in aspernatur blanditiis fugiat.', 'Et quasi amet maxime quia perspiciatis blanditiis omnis accusantium. Esse voluptatem eos excepturi et. Esse pariatur officiis aut est eveniet ipsam nisi repellat. Quasi nesciunt esse et voluptatem alias voluptatem repudiandae.', 338243, '1996-08-10 16:18:17', '1980-05-31 11:28:37', 8)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (91, 'Eum voluptatem soluta magni facere velit dolores quia necessitatibus. Tempore est iste voluptatibus id aut ad ex. Deserunt maxime ut ut libero non. Aperiam odit placeat odio incidunt.', 'At qui sint quos quasi et distinctio. Cumque doloribus quia quis enim iure excepturi. Ut molestiae et asperiores quia quo. Laborum provident illum sint doloremque.', 571107587, '2007-11-20 09:52:26', '1983-12-15 08:38:54', 2)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (92, 'Voluptates maxime tempora quas. Rerum eos reprehenderit deserunt ipsa quis. Et minus reiciendis laudantium velit voluptatem. Eos molestiae est ut autem. Et ullam vel molestiae atque qui omnis.', 'Rem harum itaque qui quod architecto qui. Quia debitis officia sint delectus ducimus consequatur. Voluptas repudiandae ducimus necessitatibus ea. Autem rerum magnam ea enim.', 40, '1999-07-07 15:00:31', '2011-11-22 17:32:41', 18)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (93, 'Magni incidunt beatae laborum necessitatibus. Libero cupiditate sed quia velit dolor voluptas assumenda. Libero et mollitia ab.', 'Voluptas quidem eos consequatur velit pariatur voluptatem consequatur. Ipsum dolorem modi voluptas sed dolorum est. Dolorum ut laudantium dolores atque et perspiciatis.', 279, '1975-03-28 03:54:54', '2006-01-07 19:48:43', 1)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (94, 'Excepturi molestiae vel similique commodi non. Ea minima recusandae qui nisi tenetur. Perferendis sed eos nam. Explicabo exercitationem qui voluptatem temporibus praesentium quasi at deserunt.', 'Qui qui molestias qui facere qui. Odio vitae qui doloribus dolorem qui ut nobis. Dolorem molestiae fugiat ad nesciunt esse cumque perspiciatis. Quia adipisci sed et esse atque et.', 2911, '1985-08-25 05:08:14', '2008-10-19 02:38:42', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (95, 'Soluta ipsa incidunt vel. Eveniet quam ut dicta exercitationem reiciendis et rerum. Ab qui excepturi dolor ut accusantium aut alias. Ullam culpa consequuntur accusantium ab veniam repellendus quis.', 'Laudantium rerum et omnis. Porro voluptatem enim aspernatur voluptas. Sed exercitationem laborum id et.', 1705, '2020-09-22 10:22:02', '1977-09-17 07:50:15', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (96, 'Veniam culpa inventore atque labore id corporis rerum. Et debitis hic consequatur facere ut est. Et exercitationem voluptate et. Laudantium distinctio sapiente officia delectus vero corporis.', 'Enim non consequatur sequi praesentium laborum fugit voluptatem. Quidem provident animi odio est quam at.', 180, '1989-04-26 12:21:24', '1988-02-01 12:25:37', 19)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (97, 'Consequatur error voluptas itaque numquam quos eos voluptatem. Recusandae hic optio dolorum sint voluptates adipisci vitae. Non enim inventore voluptates laborum sapiente deserunt.', 'Omnis dicta autem beatae sint architecto enim. Aut eveniet voluptatem quae ut est voluptatem quis. Totam ea dolorem nam sed. Dolore rem soluta placeat nobis dolorem.', 3273, '2015-10-09 04:24:11', '1996-05-10 04:00:47', 7)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (98, 'Cupiditate id ad velit ab neque quae qui. Non beatae ducimus quis asperiores. Ut et voluptas unde voluptatem. Harum et doloremque aut.', 'Eligendi porro ratione et vel animi hic mollitia. Aut alias omnis blanditiis rem. Aut illum sapiente suscipit voluptas cum facilis repudiandae.', 4311, '2021-03-07 04:37:24', '1971-05-04 21:17:10', 3)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (99, 'Error illum amet eos quasi autem est nobis. Iste ullam non illum quod. Dolorem et vitae ex rem necessitatibus.', 'Culpa quo ut eveniet. Eos laboriosam aut tenetur dolore maxime repellendus. Delectus quasi est expedita deserunt rerum harum. Non tenetur aperiam aliquid earum. Et voluptatum ea voluptates nihil harum earum aut.', 7, '2010-01-08 05:21:34', '1970-05-28 03:21:02', 4)");
        $this->addSql("INSERT INTO answer (id, content, username, votes, created_at, updated_at, question_id) VALUES (100, 'Blanditiis sed voluptas repudiandae consequatur et. Dicta vel id assumenda incidunt iste. Nam quo odio illum aut harum vel.', 'Sequi neque cupiditate voluptas consectetur a maxime. Quas aspernatur qui eius sit. Dolorem impedit rerum numquam soluta tenetur maiores soluta.', 94, '2018-02-04 23:52:34', '1978-01-21 22:16:37', 10)");
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}