monolog:
    channels: ["deprecation"]

    handlers:
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            channels: ["deprecation"]
