###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    memcached:
        container_name: sf5-ci-cd-memcached
        image : donbrico/memcached:v1.0.0

    mailhog:
        container_name: sf5-ci-cd-mailhog
        image : donbrico/mailhog:v1.0.0
        ports:
            - '2011:8025'

    redis:
        container_name: sf5-ci-cd-redis
        image : donbrico/redis-alpine:v1.0.0

    database:
        container_name: sf5-ci-cd-db
        image : donbrico/mysql-80-debian:v1.1.0
        working_dir: /application
        volumes:
            - ./phpdocker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db-sf5-p4
            MYSQL_PASSWORD: root
        ports:
            - "2012:3306"
        tty: true

    webserver:
        container_name: sf5-ci-cd-web
        image : donbrico/nginx-alpine:v1.0.0
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2010:80'

    php-fpm:
        container_name: sf5-ci-cd-php
        image : donbrico/php-fpm-81:v1.0.0
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    node:
        container_name: sf5-ci-cd-node
        image : donbrico/node-14:v1.1.0
        working_dir: /home/wwwroot/sf5-p4
        volumes:
            - .:/home/wwwroot/sf5-p4
        command: bash -c "yarn && yarn dev --watch"
        depends_on:
            - php-fpm

    phpmyadmin:
        image: donbrico/phpmyadmin:v1.0.0
        container_name: sf5-ci-cd-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        ports:
            - "2013:80"
        links:
            - database
